import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { EXTENSION_TYPE_LABELS, } from "./catalog.js";
import { buildCreationPrompt } from "./prompt.js";
import styles from './creator-center.module.css';
export function AbilityDetail({ ability, disabled, onBack, onCreate, onAskAdvisor }) {
    const prompt = buildCreationPrompt({ goal: ability.implementation.goal, template: ability });
    const isPiExtension = ability.ecosystem === 'pi';
    return (_jsxs("section", { className: styles.abilityDetail, role: "region", "aria-label": `${ability.title}详情`, children: [_jsx("button", { type: "button", className: styles.backButton, "aria-label": "\u8FD4\u56DE\u80FD\u529B\u5E93", onClick: onBack, children: "\u2190 \u8FD4\u56DE\u80FD\u529B\u5E93" }), _jsx("header", { className: styles.detailHeader, children: _jsxs("div", { children: [_jsx("h3", { tabIndex: -1, children: ability.title }), _jsx("p", { children: ability.summary })] }) }), _jsxs("div", { className: styles.detailMeta, "aria-label": "\u6765\u6E90\u4E0E\u517C\u5BB9\u4FE1\u606F", children: [_jsx("span", { children: isPiExtension ? 'Pi 热门扩展' : 'GitHub 项目' }), isPiExtension && _jsx("span", { children: "\u9762\u5411\u9AD8\u9636\u5F00\u53D1\u8005" })] }), ability.compatibility === 'manual-adapter' && (_jsx("p", { className: styles.compatibilityNotice, children: isPiExtension
                    ? '这些是 Pi 生态中使用量靠前的热门扩展，供高阶开发者选择和借鉴。它们不能直接安装到 DeepSeek Harness，但可以用 Harness 自己的 Skill、MCP、Preset 或插件机制，定制适合自己的等价扩展。'
                    : '这是其他 Agent 生态的参考项目，不能直接安装到 DeepSeek Harness。下面的添加方法会教你用 Harness 自己的 Skill、MCP、Preset 或插件机制实现等价能力。' })), _jsxs("div", { className: styles.detailIntro, children: [_jsx("span", { children: "\u9879\u76EE\u7B80\u4ECB" }), _jsxs("p", { children: [ability.outcome, " ", ability.summary] })] }), _jsxs("div", { className: styles.repositoryCard, children: [_jsxs("div", { children: [_jsx("span", { className: styles.repositoryLabel, children: "GitHub \u5F00\u6E90\u9879\u76EE" }), _jsx("a", { className: styles.repositoryUrl, href: ability.implementation.repositoryUrl, target: "_blank", rel: "noreferrer", children: ability.implementation.repositoryUrl })] }), _jsx("a", { className: styles.repositoryButton, href: ability.implementation.repositoryUrl, target: "_blank", rel: "noreferrer", children: "\u6253\u5F00\u4ED3\u5E93 \u2197" })] }), _jsxs("div", { className: styles.detailActions, children: [_jsx("button", { type: "button", className: styles.secondaryButton, onClick: onAskAdvisor, children: "\u5148\u95EE AI \u662F\u5426\u9002\u5408\u6211" }), _jsx("button", { type: "button", className: styles.primaryButton, disabled: disabled, onClick: () => { onCreate(prompt); }, children: "\u8BA9 DeepSeek \u5E2E\u6211\u521B\u5EFA" })] }), _jsxs("details", { className: styles.advanced, children: [_jsx("summary", { children: "\u9AD8\u7EA7\u4FE1\u606F" }), _jsxs("div", { className: styles.advancedBody, children: [_jsxs("div", { className: styles.implementationLine, children: [_jsx("strong", { children: "\u5B9E\u73B0\u65B9\u5F0F" }), _jsx("span", { children: ability.implementation.extensionTypes.map(type => EXTENSION_TYPE_LABELS[type]).join(' · ') })] }), _jsxs("div", { className: styles.implementationLine, children: [_jsx("strong", { children: "\u5B8C\u6210\u68C0\u67E5" }), _jsx("ul", { children: ability.implementation.checks.map(item => _jsx("li", { children: item }, item)) })] }), _jsxs("div", { className: styles.sourceLine, children: ["\u6765\u6E90\uFF1A", ability.implementation.source, " \u00B7 \u8BB8\u53EF\u8BC1\uFF1A", ability.implementation.license] }), _jsxs("label", { className: styles.promptLabel, children: ["\u5B89\u5168\u521B\u5EFA\u8BF4\u660E", _jsx("textarea", { readOnly: true, value: prompt, rows: 8 })] })] })] })] }));
}
