import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ABILITY_KINDS, ABILITY_KIND_LABELS, INDUSTRIES, INDUSTRY_LABELS, } from "./catalog.js";
import { AbilityDetail } from "./AbilityDetail.js";
import styles from './creator-center.module.css';
export function AbilityLibrary({ abilities, industry, kind, selectedId, recommendationLabel, creatorDisabled, onIndustryChange, onKindChange, onSelect, onClear, onCreate, onAskAdvisor, }) {
    const selected = abilities.find(item => item.id === selectedId);
    return (_jsxs("section", { className: styles.library, "aria-labelledby": "creator-library-title", children: [_jsxs("header", { className: styles.libraryHeader, children: [_jsxs("div", { children: [_jsx("span", { className: styles.sectionKicker, children: "\u6309\u4F60\u7684\u5DE5\u4F5C\u6765\u627E" }), _jsx("h2", { id: "creator-library-title", children: "\u80FD\u529B\u5E93" })] }), _jsx("span", { className: styles.resultCount, children: recommendationLabel ?? `找到 ${abilities.length} 个能力` })] }), _jsxs("div", { className: styles.filterRows, children: [_jsxs("div", { className: styles.filterRow, role: "group", "aria-label": "\u884C\u4E1A\u5206\u7C7B", children: [_jsx("span", { className: styles.filterLabel, children: "\u884C\u4E1A" }), _jsx("div", { children: INDUSTRIES.map(item => (_jsx("button", { type: "button", "aria-pressed": industry === item.id, onClick: () => { onIndustryChange(item.id); }, children: item.label }, item.id))) })] }), _jsxs("div", { className: styles.filterRow, role: "group", "aria-label": "\u80FD\u529B\u79CD\u7C7B", children: [_jsx("span", { className: styles.filterLabel, children: "\u79CD\u7C7B" }), _jsx("div", { children: ABILITY_KINDS.map(item => (_jsx("button", { type: "button", "aria-pressed": kind === item.id, onClick: () => { onKindChange(item.id); }, children: item.label }, item.id))) })] })] }), abilities.length === 0 ? (_jsxs("div", { className: styles.emptyState, children: [_jsx("span", { "aria-hidden": "true", children: "\u2301" }), _jsx("h3", { children: "\u6CA1\u6709\u627E\u5230\u5B8C\u5168\u5339\u914D\u7684\u80FD\u529B" }), _jsx("p", { children: "\u6362\u4E2A\u8BF4\u6CD5\uFF0C\u6216\u8005\u5148\u6E05\u9664\u884C\u4E1A\u548C\u79CD\u7C7B\u6761\u4EF6\u3002" }), _jsxs("div", { children: [_jsx("button", { type: "button", className: styles.secondaryButton, onClick: onClear, children: "\u6E05\u9664\u7B5B\u9009" }), _jsx("button", { type: "button", className: styles.textButton, onClick: onAskAdvisor, children: "\u8BA9 AI \u5E2E\u6211\u5B9A\u5236" })] })] })) : (_jsx("div", { className: styles.abilityGrid, children: abilities.map(ability => {
                    const cardIndustry = industry !== 'all' && ability.industryIds.includes(industry)
                        ? industry
                        : ability.industryIds[0];
                    return (_jsxs("article", { className: `${styles.abilityCard} ${selectedId === ability.id ? styles.abilityCardSelected : ''}`, "data-testid": "ability-card", children: [_jsx("div", { className: styles.cardMarker, "aria-hidden": "true", children: ability.title.slice(0, 1) }), _jsx("h3", { children: ability.title }), _jsx("p", { className: styles.cardOutcome, children: ability.outcome }), _jsxs("dl", { className: styles.cardFacts, children: [_jsxs("div", { children: [_jsx("dt", { children: "\u4F60\u63D0\u4F9B" }), _jsx("dd", { children: ability.userProvides })] }), _jsxs("div", { children: [_jsx("dt", { children: "\u4F60\u5F97\u5230" }), _jsx("dd", { children: ability.userReceives })] })] }), _jsxs("footer", { className: styles.cardFooter, children: [_jsxs("div", { className: styles.cardTags, children: [_jsx("span", { children: cardIndustry === undefined ? '通用' : INDUSTRY_LABELS[cardIndustry] }), _jsx("span", { children: ABILITY_KIND_LABELS[ability.kindIds[0]] })] }), _jsxs("button", { type: "button", "aria-expanded": selectedId === ability.id, "aria-label": `查看“${ability.title}”方案`, onClick: () => { onSelect(selectedId === ability.id ? null : ability.id); }, children: ["\u67E5\u770B\u65B9\u6848 ", _jsx("span", { "aria-hidden": "true", children: "\u2192" })] })] })] }, ability.id));
                }) })), selected !== undefined && (_jsx(AbilityDetail, { ability: selected, disabled: creatorDisabled, onClose: () => { onSelect(null); }, onCreate: onCreate, onAskAdvisor: onAskAdvisor }))] }));
}
