import { DEVELOPER_DIRECTIONS_BY_ABILITY_ID, } from "./developer-directions.js";
function repoAbility(seed) {
    return {
        ...seed,
        developerDirectionIds: seed.developerDirectionIds ?? DEVELOPER_DIRECTIONS_BY_ABILITY_ID[seed.id] ?? [],
        userProvides: seed.userProvides ?? '你的目标、项目位置和希望 AI 完成的具体任务。',
        userReceives: seed.userReceives ?? '一套可以按步骤添加、验证和关闭的能力。',
        suitableFor: seed.suitableFor ?? '你想让 DeepSeek Harness 多做一类明确的工作。',
        readsOrChanges: seed.readsOrChanges ?? '只读取你指定的项目或公开来源；远程写操作需要你单独确认。',
        rollback: seed.rollback ?? '停用对应 Skill、删除 MCP 配置或按项目变更清单回退。',
        estimatedTime: seed.estimatedTime ?? '约 5–20 分钟',
    };
}
function shortAbility(seed) {
    return repoAbility({
        id: seed.id,
        title: seed.title,
        outcome: seed.outcome,
        summary: seed.summary,
        industryIds: seed.industryIds,
        kindIds: seed.kindIds,
        collectionIds: [],
        aliases: seed.aliases,
        examples: seed.examples,
        ecosystem: seed.ecosystem,
        trust: seed.trust,
        compatibility: seed.compatibility,
        popularity: seed.popularity,
        implementation: {
            extensionTypes: seed.extensionTypes,
            goal: seed.goal,
            addMethod: seed.addMethod,
            checks: seed.checks,
            source: seed.source,
            license: seed.license,
            repositoryUrl: seed.repositoryUrl,
        },
    });
}
const OFFICIAL_REPO = 'https://github.com/deepseek-ai/deepseek-harness';
const DSH_CHECKS = ['先确认当前 Harness 版本、运行平面和所需权限', '只在你确认后写入用户自己的 Skill、MCP、preset 或插件配置', '完成后提供启用、验证、停用和回滚方法'];
export const ADDITIONAL_ABILITIES = [
    repoAbility({
        id: 'dsh-official-create-skill',
        title: 'DeepSeek Harness：创建自己的 Skill',
        outcome: '把你反复使用的一套做事方法，变成 Harness 可以按需调用的 Skill。',
        summary: '官方机制配方：先用创造模式检查运行时，再生成用户目录中的 SKILL.md。',
        industryIds: ['programmer', 'education', 'retail', 'government'],
        kindIds: ['coding', 'research', 'content-creation'],
        collectionIds: [],
        aliases: ['官方 Skill 教程', '创建 Skill', 'SKILL.md', '自定义能力'],
        examples: ['把我的电商客服流程做成 Skill', '让 AI 每次写代码前都先检查清单'],
        ecosystem: 'deepseek-harness',
        trust: 'dsh-official',
        compatibility: 'creator-recipe',
        popularity: 'GitHub 约 126.8K 星；DeepSeek Harness 官方仓库',
        implementation: {
            extensionTypes: ['skill'],
            goal: '请使用 DeepSeek Harness 官方 Skill 机制，先检查当前运行时和用户 Skill 目录，再帮我把下面这套重复工作整理成一个最小可用的 SKILL.md。不要直接运行远程脚本，先展示文件和验证方法。',
            addMethod: '进入创造模式，复制这段创建说明，先让 Harness 检查 .dsh/skills、.agents/skills 和当前预设，再确认是否写入一个独立的 SKILL.md。',
            checks: DSH_CHECKS,
            source: 'DeepSeek Harness 官方文档与仓库',
            license: 'MIT',
            repositoryUrl: OFFICIAL_REPO,
        },
    }),
    repoAbility({
        id: 'dsh-official-connect-mcp',
        title: 'DeepSeek Harness：连接一个 MCP 服务',
        outcome: '把浏览器、GitHub、数据库或其他外部工具接入 Harness。',
        summary: '官方机制配方：创建 MCP 客户端插件，明确命令、环境变量、权限和停用方法。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'retail'],
        kindIds: ['agents', 'research', 'data-analysis'],
        collectionIds: [],
        aliases: ['官方 MCP 教程', 'MCP', '连接工具', '外部服务'],
        examples: ['把 GitHub 接到 Harness', '连接一个只读数据库'],
        ecosystem: 'deepseek-harness',
        trust: 'dsh-official',
        compatibility: 'mcp',
        popularity: 'GitHub 约 126.8K 星；DeepSeek Harness 官方仓库',
        implementation: {
            extensionTypes: ['plugin'],
            goal: '请按照 DeepSeek Harness 官方 MCP 客户端机制，帮我设计一个最小权限的工具连接。先列出 transport、serverName、command、args、env 或 URL、headers，再等我确认后写配置。',
            addMethod: '复制说明进入创造模式，先让 Harness 解释这个 MCP 会暴露哪些工具、需要什么密钥、能否只读，再决定是否创建连接。',
            checks: DSH_CHECKS,
            source: 'DeepSeek Harness MCP Client 官方文档',
            license: 'MIT',
            repositoryUrl: OFFICIAL_REPO,
        },
    }),
    repoAbility({
        id: 'dsh-official-custom-agent-preset',
        title: 'DeepSeek Harness：定制 Agent Preset',
        outcome: '给某一类会话配置专属工具、提示词、角色和工作边界。',
        summary: '官方机制配方：复制已有 preset 后创建用户自己的版本，不直接改官方内置 preset。',
        industryIds: ['programmer', 'retail', 'education', 'government'],
        kindIds: ['coding', 'content-creation', 'agents'],
        collectionIds: [],
        aliases: ['Agent Preset', '会话预设', '自定义 Agent', '专业助手'],
        examples: ['做一个电商运营 Agent', '做一个只读代码审查 Agent'],
        ecosystem: 'deepseek-harness',
        trust: 'dsh-official',
        compatibility: 'creator-recipe',
        popularity: 'GitHub 约 126.8K 星；DeepSeek Harness 官方仓库',
        implementation: {
            extensionTypes: ['agent-preset'],
            goal: '请复制一个官方 Agent Preset 作为用户版本，帮我设计它的工具、Skill、系统提示词、权限边界和验证任务。不要修改 shipped preset。',
            addMethod: '在创造模式中先描述用途和禁止事项，让 Harness 复制到用户 preset 目录；空白会话里切换并做一次低风险验收。',
            checks: DSH_CHECKS,
            source: 'DeepSeek Harness 官方 Agent Preset 文档',
            license: 'MIT',
            repositoryUrl: OFFICIAL_REPO,
        },
    }),
    repoAbility({
        id: 'dsh-official-ui-extension',
        title: 'DeepSeek Harness：增加一个设置或 UI 扩展',
        outcome: '在不改官方页面源码的情况下增加设置区、侧边栏入口或小组件。',
        summary: '官方机制配方：使用 Slots、theme tokens 和 settings.section 注册 UI，不猜 DOM 选择器。',
        industryIds: ['programmer', 'retail', 'education'],
        kindIds: ['coding', 'agents'],
        collectionIds: [],
        aliases: ['UI 插件', '设置页面', '侧边栏入口', 'Slots', 'theme tokens'],
        examples: ['给 Harness 增加一个 Skill Hub 页面', '增加主题切换设置'],
        ecosystem: 'deepseek-harness',
        trust: 'dsh-official',
        compatibility: 'creator-recipe',
        popularity: 'GitHub 约 126.8K 星；DeepSeek Harness 官方仓库',
        implementation: {
            extensionTypes: ['ui-extension'],
            goal: '请使用 DeepSeek Harness 官方 UI 扩展机制，先查询当前 slots、theme tokens 和 settings.section，再设计一个不破坏官方 UI 的小扩展。先输出包结构和回滚方式，等待确认后再创建。',
            addMethod: '进入 Creator Mode，先让 Harness 检查实时运行时中的可用 UI 扩展点，再生成版本化插件；不要使用猜测的 CSS 选择器或覆盖官方源码。',
            checks: DSH_CHECKS,
            source: 'DeepSeek Harness 官方 Extension Cookbook',
            license: 'MIT',
            repositoryUrl: OFFICIAL_REPO,
        },
    }),
    repoAbility({
        id: 'dsh-official-plugin-audit',
        title: 'DeepSeek Harness：扩展审计与回滚配方',
        outcome: '在添加一个 Skill 或插件前，先检查它会访问什么、改什么，以及如何撤销。',
        summary: '针对 Harness 自由扩展特点设计的安全流程卡，不是第三方安装器。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'government'],
        kindIds: ['agents', 'coding'],
        collectionIds: [],
        aliases: ['扩展审计', '权限检查', '回滚', '插件安全', '安全安装'],
        examples: ['这个 GitHub 插件能不能安全使用', '帮我审计一个 MCP 配置'],
        ecosystem: 'deepseek-harness',
        trust: 'dsh-official',
        compatibility: 'creator-recipe',
        popularity: 'GitHub 约 126.8K 星；DeepSeek Harness 官方仓库',
        implementation: {
            extensionTypes: ['workflow', 'plugin'],
            goal: '请先审计我准备加入 DeepSeek Harness 的 Skill、MCP 或插件：来源、许可证、安装脚本、权限、网络访问、写入范围、版本固定、验证命令和回滚步骤。没有明确风险时不要执行。',
            addMethod: '将第三方仓库地址粘贴到创造模式，让 Harness 先输出审计清单和风险等级，再由我决定是否创建适配版本。',
            checks: ['固定仓库版本或 commit，不直接追踪 main', '不把密钥写进 prompt、仓库或日志', '先做只读/最小范围测试，再决定是否长期启用'],
            source: 'DeepSeek Harness 官方插件与 Creator Mode 机制',
            license: 'MIT',
            repositoryUrl: OFFICIAL_REPO,
        },
    }),
    repoAbility({
        id: 'pi-mcp-adapter',
        title: 'nicobailon/pi-mcp-adapter',
        outcome: '让 Pi 连接 MCP 服务的适配器，适合研究 MCP 工具如何接入 Agent。',
        summary: 'Pi 官方目录中使用量靠前的 MCP 适配器；在 Harness 中应参考能力边界，按 DSH MCP Client 机制重配。',
        industryIds: ['programmer', 'financial-services', 'retail'],
        kindIds: ['agents', 'research'],
        collectionIds: [],
        aliases: ['Pi MCP Adapter', 'MCP 适配器', 'Pi 扩展'],
        examples: ['参考 Pi 的 MCP 连接方式', '把一个 MCP 服务接入 Harness'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'manual-adapter',
        popularity: 'Pi 目录约 354.4K 月下载；GitHub 约 1.2K 星',
        implementation: {
            extensionTypes: ['plugin'],
            goal: '请阅读 nicobailon/pi-mcp-adapter 的公开说明，只提炼它的 MCP 连接思路；不要把 Pi 扩展直接安装到 Harness。请用 DSH 官方 MCP Client 机制设计等价连接，并先列出权限和回滚。',
            addMethod: '先打开 GitHub README 了解 Pi 的实现，再让 Creator Mode 按 DSH MCP 配置生成适配方案；如果已有原生 MCP 连接，优先复用原生连接。',
            checks: ['明确标注 Pi 与 Harness 的运行时差异', '列出 MCP 工具名、权限和密钥来源', '用一个只读工具做最小验证'],
            source: 'Pi 官方 Package Catalog / 维护者仓库',
            license: 'MIT',
            repositoryUrl: 'https://github.com/nicobailon/pi-mcp-adapter',
        },
    }),
    repoAbility({
        id: 'pi-web-access',
        title: 'nicobailon/pi-web-access',
        outcome: '为 Agent 增加网页搜索、URL 抓取、GitHub 克隆和 PDF 提取等研究能力。',
        summary: 'Pi 官方目录使用量很高的联网扩展；Harness 应优先采用官方 Web Search、Firecrawl 或 MCP 等价方案。',
        industryIds: ['programmer', 'financial-services', 'life-sciences', 'retail', 'education'],
        kindIds: ['research'],
        collectionIds: [],
        aliases: ['Pi Web Access', '网页搜索', 'URL 抓取', 'PDF 提取'],
        examples: ['查最新技术文档', '读取一批公开网页和 PDF'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'manual-adapter',
        popularity: 'Pi 目录约 258K 月下载；GitHub 约 1.1K 星',
        implementation: {
            extensionTypes: ['plugin', 'skill'],
            goal: '请参考 pi-web-access 的公开能力，帮我选择 DeepSeek Harness 已有 Web Search、Firecrawl MCP 或其他只读连接来实现同等需求。不要直接安装 Pi 扩展。',
            addMethod: '先选择需要的能力：搜索、抓 URL、PDF、GitHub 或视频；再让 Creator Mode 只配置缺失的 DSH Skill/MCP，不一次性复制整套。',
            checks: ['显示来源 URL 和日期', '限制访问范围和请求频率', '不自动登录、发帖或提交远程表单'],
            source: 'Pi 官方 Package Catalog / 维护者仓库',
            license: 'MIT',
            repositoryUrl: 'https://github.com/nicobailon/pi-web-access',
        },
    }),
    repoAbility({
        id: 'pi-subagents',
        title: 'nicobailon/pi-subagents',
        outcome: '研究 Pi 如何把任务委派给隔离的子 Agent，并返回摘要或产物。',
        summary: 'Pi 目录中使用量和 GitHub 星数都较高的子 Agent 扩展；Harness 已有 subagents/workflows，适合作为对照。',
        industryIds: ['programmer', 'retail', 'education'],
        kindIds: ['agents', 'coding'],
        collectionIds: [],
        aliases: ['Pi Subagents', '子 Agent', '任务委派', '并行任务'],
        examples: ['让多个 Agent 分头研究', '把审查和实现拆开'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'manual-adapter',
        popularity: 'Pi 目录约 40.4K 月下载；GitHub 约 3.2K 星',
        implementation: {
            extensionTypes: ['plugin', 'workflow'],
            goal: '请比较 pi-subagents 与 DeepSeek Harness 已有的 subagents、workflows、Ralph 能力，指出是否真的缺功能；只有存在明确差距时才设计 DSH 原生补充。',
            addMethod: '不要直接安装 Pi 扩展。先让 Harness 做能力对照表，再用官方 preset/workflow 机制创建最小差异补丁。',
            checks: ['明确子 Agent 的上下文、权限和成本边界', '避免重复安装已有 Harness 能力', '保留取消、超时和结果审查入口'],
            source: 'Pi 官方 Package Catalog / 维护者仓库',
            license: 'MIT',
            repositoryUrl: 'https://github.com/nicobailon/pi-subagents',
        },
    }),
    repoAbility({
        id: 'pi-lens',
        title: 'apmantza/pi-lens',
        outcome: '把 LSP、lint、格式化和类型检查结果变成持续的代码反馈。',
        summary: '适合研究“每次改动后自动检查”的 Agent 体验；Harness 中可通过项目级命令、Hook 或插件实现。',
        industryIds: ['programmer'],
        kindIds: ['coding', 'data-analysis'],
        collectionIds: [],
        aliases: ['Pi Lens', 'LSP', 'lint', '类型检查', '代码反馈'],
        examples: ['每次修改代码后自动跑检查', '让 AI 及时看到类型错误'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'manual-adapter',
        popularity: 'Pi 目录约 40.9K 月下载；GitHub 约 322 星',
        implementation: {
            extensionTypes: ['plugin', 'workflow'],
            goal: '请参考 pi-lens 的反馈思路，检查当前 Harness 是否可以用项目脚本、Hook 或官方插件实现。先设计只读检查和失败回传，不直接运行未知命令。',
            addMethod: '让 Creator Mode 先读取项目已有 lint、test、typecheck 命令，再生成一个项目级验证工作流；不要把 Pi 扩展直接复制到 Harness。',
            checks: ['只运行项目已声明或用户确认的命令', '错误输出截断并保留关键位置', '验证失败时不宣称任务完成'],
            source: 'Pi 官方 Package Catalog / 维护者仓库',
            license: 'MIT',
            repositoryUrl: 'https://github.com/apmantza/pi-lens',
        },
    }),
    repoAbility({
        id: 'pi-hermes-memory',
        title: 'chandra447/pi-hermes-memory',
        outcome: '给 Agent 增加跨会话记忆、会话搜索和经验沉淀。',
        summary: 'Pi 的持久化记忆扩展；Harness 已有会话持久化，但不等于完整的跨会话知识库。',
        industryIds: ['programmer', 'retail', 'education'],
        kindIds: ['agents', 'research'],
        collectionIds: [],
        aliases: ['Pi Hermes Memory', '长期记忆', '会话搜索', '经验沉淀'],
        examples: ['记住我的项目约定', '搜索过去的工作记录'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'manual-adapter',
        popularity: 'Pi 目录约 24.7K 月下载；GitHub 约 340 星',
        implementation: {
            extensionTypes: ['plugin', 'skill'],
            goal: '请区分 DeepSeek Harness 的会话历史、用户 Skill 和真正的跨会话记忆，再参考 pi-hermes-memory 设计一个最小、可审查、可删除的记忆方案。不要默认保存敏感信息。',
            addMethod: '先选择只保存项目约定、工作偏好还是研究笔记；让 Creator Mode 生成可查看、可删除、可导出的存储方案。',
            checks: ['明确保存位置和数据范围', '敏感信息默认不写入记忆', '提供搜索、导出、清空和停用方法'],
            source: 'Pi 官方 Package Catalog / 维护者仓库',
            license: 'MIT',
            repositoryUrl: 'https://github.com/chandra447/pi-hermes-memory',
        },
    }),
    repoAbility({
        id: 'pi-plan-mode',
        title: 'qmx/pi-plan-mode',
        outcome: '研究 Pi 如何增加只读规划模式，让 Agent 先说明方案再执行。',
        summary: 'Harness 已内置 Plan Mode，因此这里作为对照和设计参考，不建议重复安装。',
        industryIds: ['programmer', 'education'],
        kindIds: ['coding', 'agents'],
        collectionIds: [],
        aliases: ['Pi Plan Mode', '只读计划', '规划模式'],
        examples: ['先看方案不改文件', '让 AI 先列实施计划'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'manual-adapter',
        popularity: 'Pi 目录约 19.2K 月下载；GitHub 约 20 星',
        implementation: {
            extensionTypes: ['agent-preset', 'workflow'],
            goal: '请对比 qmx/pi-plan-mode 与 DeepSeek Harness 已有 Plan Mode，确认当前项目是否需要额外规则；如果不需要，只生成使用教程，不创建重复插件。',
            addMethod: '直接使用 Harness 内置 Plan Mode；只有发现明确缺口时，才让 Creator Mode 生成用户级 preset 或工作流。',
            checks: ['规划阶段不写入文件', '执行前列出范围和验证命令', '明确从计划到执行的切换动作'],
            source: 'Pi 官方 Package Catalog / 维护者仓库',
            license: '未知；添加前需核验仓库许可证',
            repositoryUrl: 'https://github.com/qmx/pi-plan-mode',
        },
    }),
    repoAbility({
        id: 'pi-ask-user',
        title: 'edlsh/pi-ask-user',
        outcome: '让 Agent 在不确定时用结构化选项询问用户，而不是自行猜测。',
        summary: '很适合转化为 Harness 的“小白友好”交互配方，但不能直接把 Pi 扩展装进 Harness。',
        industryIds: ['programmer', 'retail', 'education', 'government'],
        kindIds: ['agents'],
        collectionIds: [],
        aliases: ['ask user', '结构化提问', '多选问题', '澄清需求'],
        examples: ['需求不清时先问我三个选项', '让我选择安装范围'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'manual-adapter',
        popularity: 'Pi 目录约 10.4K 月下载；GitHub 约 138 星',
        implementation: {
            extensionTypes: ['plugin', 'ui-extension'],
            goal: '请参考 pi-ask-user 的结构化提问思路，设计一个符合 DeepSeek Harness UI 和 Agent API 的用户确认步骤。不要直接安装 Pi 扩展。',
            addMethod: '优先复用 Harness 官方 ask-user 能力；若当前 preset 缺失，再让 Creator Mode 创建一个最小的确认工具或 UI 扩展。',
            checks: ['问题用小白能懂的语言', '危险操作必须显式确认', '保留自由输入和取消选项'],
            source: 'Pi 官方 Package Catalog / 维护者仓库',
            license: 'MIT',
            repositoryUrl: 'https://github.com/edlsh/pi-ask-user',
        },
    }),
    repoAbility({
        id: 'pi-skills-collection',
        title: 'badlogic/pi-skills',
        outcome: '一组适合研究和个人工作流的 Pi Skill，包括浏览器、搜索、云盘、邮箱和转写。',
        summary: '维护者 Skill 集合；Harness 要逐个复制 Skill 目录，不能把整仓库放进深层目录后期待自动发现。',
        industryIds: ['programmer', 'retail', 'education', 'life-sciences'],
        kindIds: ['research', 'content-creation', 'agents'],
        collectionIds: [],
        aliases: ['pi-skills', 'browser-tools', 'brave-search', 'transcribe', 'youtube-transcript', 'Google Drive', 'Gmail'],
        examples: ['给 Harness 增加 YouTube 字幕整理', '把 Google Drive 文件交给 Agent 研究'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'skill-copy',
        popularity: 'GitHub 约 2.4K 星；维护者公开 Skill 集合',
        implementation: {
            extensionTypes: ['skill'],
            goal: '请阅读 badlogic/pi-skills，先列出其中每个 Skill 的职责、依赖和许可证，再选择一个复制为 DeepSeek Harness 的一层用户 Skill。不要整仓库盲目克隆。',
            addMethod: '在详情页选择具体 Skill 后，按目录级说明复制对应 SKILL.md 到 .dsh/skills/<name> 或 .agents/skills/<name>，完成后用一个真实任务验证。',
            checks: ['逐个 Skill 检查依赖和许可证', '遵守 Harness 一层目录发现规则', '需要账号的 Skill 单独说明密钥和撤销方法'],
            source: 'Pi 维护者公开 Skill 集合',
            license: 'MIT',
            repositoryUrl: 'https://github.com/badlogic/pi-skills',
        },
    }),
    repoAbility({
        id: 'pi-skill-browser-tools',
        title: 'pi-skills/browser-tools',
        outcome: '给 Agent 一个浏览器研究和验证的 Skill 参考。',
        summary: '来自 pi-skills 集合的单项 Skill；在 Harness 中优先转成 Playwright MCP 或项目级浏览器工具。',
        industryIds: ['programmer', 'retail', 'education'],
        kindIds: ['research', 'agents'],
        collectionIds: [],
        aliases: ['browser-tools', '浏览器研究', '网页验证'],
        examples: ['打开网页找出关键信息', '验证页面上的按钮和链接'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'skill-copy',
        popularity: '来自 GitHub 约 2.4K 星的 pi-skills 集合',
        implementation: {
            extensionTypes: ['skill'],
            goal: '请提取 pi-skills/browser-tools 的工作方法，检查当前 Harness 是否已有 Playwright MCP 或浏览器工具；有就写使用教程，没有再生成最小 Skill。',
            addMethod: '复制具体 Skill 的说明到用户 Skill 目录，或直接使用 Playwright MCP；不要把 Pi 专属命令原样执行。',
            checks: ['只访问用户允许的页面', '不自动登录或提交表单', '输出页面 URL 和验证结果'],
            source: 'Pi 维护者 Skill 集合中的单项能力',
            license: 'MIT',
            repositoryUrl: 'https://github.com/badlogic/pi-skills',
        },
    }),
    repoAbility({
        id: 'pi-skill-brave-search',
        title: 'pi-skills/brave-search',
        outcome: '让 Agent 使用 Brave Search 做带来源的公开资料搜索。',
        summary: '适合做研究能力示例；需要 API key，应该按 Harness MCP/Skill 规则重新配置。',
        industryIds: ['programmer', 'financial-services', 'life-sciences', 'education'],
        kindIds: ['research'],
        collectionIds: [],
        aliases: ['brave-search', '搜索 API', '资料检索'],
        examples: ['查一个技术库的最新文档', '搜索近期行业资料'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'skill-copy',
        popularity: '来自 GitHub 约 2.4K 星的 pi-skills 集合',
        implementation: {
            extensionTypes: ['skill', 'plugin'],
            goal: '请参考 pi-skills/brave-search，先说明 Brave Search API key 的存储方式和费用，再设计一个 DeepSeek Harness 只读搜索 Skill 或 MCP。',
            addMethod: '优先让 Creator Mode 生成用户级环境变量说明和来源引用规则；密钥由用户自己填写，不写进 Skill 文件。',
            checks: ['每个结论保留来源和日期', '密钥不进入 prompt、日志和 Git', '搜索失败时明确告诉用户'],
            source: 'Pi 维护者 Skill 集合中的单项能力',
            license: 'MIT',
            repositoryUrl: 'https://github.com/badlogic/pi-skills',
        },
    }),
    repoAbility({
        id: 'pi-skill-transcribe',
        title: 'pi-skills/transcribe',
        outcome: '把音频转成文字，再交给 Harness 做摘要、提取待办和整理。',
        summary: '适合教育、会议、内容和客服场景；需先确认本地模型或 API 依赖。',
        industryIds: ['education', 'retail', 'life-sciences', 'government'],
        kindIds: ['content-creation', 'research'],
        collectionIds: [],
        aliases: ['transcribe', '语音转文字', '会议转写', '音频整理'],
        examples: ['整理一段访谈录音', '把课程音频变成笔记'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'skill-copy',
        popularity: '来自 GitHub 约 2.4K 星的 pi-skills 集合',
        implementation: {
            extensionTypes: ['skill'],
            goal: '请参考 pi-skills/transcribe，先确认音频格式、模型或 API、隐私范围和输出目录，再为 DeepSeek Harness 设计一个可关闭的转写工作流。',
            addMethod: '复制 Skill 说明或使用本地转写工具；先处理一段无敏感信息的样本，再决定是否接入日常工作流。',
            checks: ['先说明音频是否会离开本机', '保留原文件和生成文件的对应关系', '对人名、数字和专业术语标注需复核'],
            source: 'Pi 维护者 Skill 集合中的单项能力',
            license: 'MIT',
            repositoryUrl: 'https://github.com/badlogic/pi-skills',
        },
    }),
    repoAbility({
        id: 'pi-skill-youtube-transcript',
        title: 'pi-skills/youtube-transcript',
        outcome: '提取公开视频字幕，让 Harness 能按时间段总结和引用。',
        summary: '适合教育、竞品研究和内容创作；只处理公开内容，不绕过访问限制。',
        industryIds: ['education', 'retail', 'programmer'],
        kindIds: ['research', 'content-creation'],
        collectionIds: [],
        aliases: ['youtube-transcript', 'YouTube 字幕', '视频研究'],
        examples: ['总结一条技术视频', '提取视频中的产品观点'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'skill-copy',
        popularity: '来自 GitHub 约 2.4K 星的 pi-skills 集合',
        implementation: {
            extensionTypes: ['skill'],
            goal: '请参考 pi-skills/youtube-transcript，设计一个只处理公开视频字幕的 DeepSeek Harness Skill。输出需带视频链接、时间段和无法获取字幕时的替代方案。',
            addMethod: '复制单项 Skill 说明或使用已有字幕工具；先用一条公开、允许访问的视频验证。',
            checks: ['保留视频 URL 和时间段', '不下载或传播用户未授权的内容', '字幕缺失时不编造原话'],
            source: 'Pi 维护者 Skill 集合中的单项能力',
            license: 'MIT',
            repositoryUrl: 'https://github.com/badlogic/pi-skills',
        },
    }),
    repoAbility({
        id: 'pi-skill-cloud-connectors',
        title: 'pi-skills/gccli · gdcli · gmcli',
        outcome: '把 Google Calendar、Drive 和 Gmail 的读取整理能力带入 Agent 工作流。',
        summary: '适合教育、运营和个人助理；涉及账号权限，第一版只推荐只读配置。',
        industryIds: ['education', 'retail', 'government'],
        kindIds: ['agents', 'research', 'content-creation'],
        collectionIds: [],
        aliases: ['Google Calendar', 'Google Drive', 'Gmail', '云盘', '邮箱', '日历'],
        examples: ['整理本周会议和资料', '从 Drive 找到项目文件并摘要'],
        ecosystem: 'pi',
        trust: 'maintainer',
        compatibility: 'skill-copy',
        popularity: '来自 GitHub 约 2.4K 星的 pi-skills 集合',
        implementation: {
            extensionTypes: ['skill', 'plugin'],
            goal: '请从 pi-skills 中选择 gccli、gdcli 或 gmcli，先给我画出最小权限和只读范围，再设计 DeepSeek Harness 的等价连接。不要默认打开发送邮件、删除文件或修改日历。',
            addMethod: '先选一个服务，按照官方 OAuth 或 MCP 方式配置；完成“查一封邮件/读一个文件/看一个日程”的只读测试后再扩大权限。',
            checks: ['默认只读', '显示账号和数据范围', '提供撤销 OAuth、停用连接和清理缓存方法'],
            source: 'Pi 维护者 Skill 集合中的 Google 连接能力',
            license: 'MIT',
            repositoryUrl: 'https://github.com/badlogic/pi-skills',
        },
    }),
    repoAbility({
        id: 'microsoft-playwright-mcp',
        title: 'microsoft/playwright-mcp',
        outcome: '让 Harness 通过 MCP 操作浏览器、检查页面和完成网页测试。',
        summary: 'Microsoft 官方 Playwright MCP，适合程序员、电商和网页验证。',
        industryIds: ['programmer', 'retail', 'education', 'government'],
        kindIds: ['agents', 'research', 'coding'],
        collectionIds: [],
        aliases: ['Playwright MCP', '浏览器 MCP', '网页测试', '网页自动化'],
        examples: ['打开一个网页并验证内容', '给后台系统做回归测试'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'mcp',
        popularity: 'GitHub 约 36.2K 星；Microsoft 官方项目',
        implementation: {
            extensionTypes: ['plugin'],
            goal: '请按 Microsoft Playwright MCP 和 DeepSeek Harness MCP Client 官方机制，设计一个最小浏览器连接。只访问我指定的页面，先用一个只读测试验证。',
            addMethod: '打开 GitHub README 核对 Node、浏览器和运行命令；进入创造模式创建 MCP 配置，先测试页面读取，不自动提交表单。',
            checks: ['只访问允许的网站和页面', '不绕过登录、验证码或访问控制', '提供停止进程、删除配置和清理浏览器数据方法'],
            source: 'Microsoft 官方开源 MCP Server',
            license: 'Apache-2.0',
            repositoryUrl: 'https://github.com/microsoft/playwright-mcp',
        },
    }),
    repoAbility({
        id: 'github-mcp-server',
        title: 'github/github-mcp-server',
        outcome: '让 Harness 读取和管理 GitHub 仓库、Issue、Pull Request 与代码。',
        summary: 'GitHub 官方 MCP Server；适合程序员团队和开源项目维护。',
        industryIds: ['programmer', 'education', 'government'],
        kindIds: ['coding', 'agents', 'research'],
        collectionIds: [],
        aliases: ['GitHub MCP', 'Issue', 'Pull Request', '代码仓库'],
        examples: ['总结一个仓库的 Issue', '帮我检查 PR 是否完成'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'mcp',
        popularity: 'GitHub 约 32.3K 星；GitHub 官方项目',
        implementation: {
            extensionTypes: ['plugin'],
            goal: '请按 GitHub 官方 MCP Server 和 Harness MCP Client 机制，帮我配置一个最小权限连接。先说明需要访问哪些仓库和是否只读，不自动创建 Issue 或合并 PR。',
            addMethod: '先阅读 GitHub 官方 README，创建只读或限制仓库范围的 token；在 Creator Mode 中配置后只做仓库、Issue 和 PR 查询测试。',
            checks: ['token 只授予必要仓库和权限', '写操作每次单独确认', '停用 token 后 Harness 不再保留可用凭据'],
            source: 'GitHub 官方 MCP Server',
            license: 'MIT',
            repositoryUrl: 'https://github.com/github/github-mcp-server',
        },
    }),
    repoAbility({
        id: 'upstash-context7',
        title: 'upstash/context7',
        outcome: '给 AI 提供较新的库文档，减少使用过时 API 的问题。',
        summary: '高星开源文档 MCP；适合程序员在写代码前查询当前版本的官方文档。',
        industryIds: ['programmer', 'education'],
        kindIds: ['research', 'coding'],
        collectionIds: [],
        aliases: ['Context7', '最新文档', '库文档', 'API 文档'],
        examples: ['查当前 React API', '确认一个库最新安装方法'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'mcp',
        popularity: 'GitHub 约 60.8K 星',
        implementation: {
            extensionTypes: ['plugin'],
            goal: '请评估 Context7 是否适合当前 DeepSeek Harness，再按官方 MCP Client 机制配置。回答技术问题时优先查当前文档，并保留文档来源和版本。',
            addMethod: '在 Creator Mode 中添加 Context7 MCP 连接，先查询一个明确的库和版本；不要把文档查询结果当成对本项目代码的自动修改授权。',
            checks: ['记录文档来源和版本', '查不到当前版本时明确说明', '只把查询结果作为实现依据，不自动扩大改动范围'],
            source: 'Upstash 开源文档 MCP',
            license: 'MIT',
            repositoryUrl: 'https://github.com/upstash/context7',
        },
    }),
    repoAbility({
        id: 'microsoft-markitdown',
        title: 'microsoft/markitdown',
        outcome: '把 PDF、Word、Excel、PPT、网页等文件转换成便于 AI 阅读的 Markdown。',
        summary: 'Microsoft 高星文档转换工具，适合资料研究、教育、运营和办公自动化。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'life-sciences', 'retail', 'government', 'education'],
        kindIds: ['research', 'data-analysis', 'content-creation'],
        collectionIds: [],
        aliases: ['MarkItDown', 'PDF', 'Word', 'Excel', 'PPT', '文档解析'],
        examples: ['把一批 PDF 整理成笔记', '提取 Excel 内容做分析'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'project-tool',
        popularity: 'GitHub 约 174K 星；Microsoft 官方项目',
        implementation: {
            extensionTypes: ['plugin', 'skill'],
            goal: '请参考 Microsoft MarkItDown，帮我在一个隔离项目中设计文件转 Markdown 流程。先确认输入文件范围、输出目录和是否包含敏感信息，不覆盖原文件。',
            addMethod: '在项目级环境安装并验证 MarkItDown，再让 Harness 调用明确的转换命令；不要因为安装了能力就自动扫描整个硬盘。',
            checks: ['明确输入和输出目录', '原文件只读且保留', '表格、图片、页码和引用信息缺失时标记出来'],
            source: 'Microsoft 官方开源文档转换工具',
            license: 'MIT',
            repositoryUrl: 'https://github.com/microsoft/markitdown',
        },
    }),
    repoAbility({
        id: 'stripe-ai',
        title: 'stripe/ai',
        outcome: '把 Stripe 支付、账单和 AI 产品集成能力接入开发工作流。',
        summary: 'Stripe 官方 AI 工具和 MCP 相关项目；适合电商和 SaaS 开发，不是财务自动决策工具。',
        industryIds: ['financial-services', 'retail', 'programmer'],
        kindIds: ['coding', 'agents', 'data-analysis'],
        collectionIds: [],
        aliases: ['Stripe AI', '支付', '账单', '结账', 'SaaS'],
        examples: ['给 SaaS 加支付流程', '检查 Stripe 集成代码'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'mcp',
        popularity: 'GitHub 约 1.7K 星；Stripe 官方项目',
        implementation: {
            extensionTypes: ['plugin', 'skill'],
            goal: '请阅读 Stripe AI 官方项目，帮我设计一个最小权限的开发辅助连接。只做文档查询、测试环境和代码审查，不触碰生产资金或真实客户数据。',
            addMethod: '先使用测试密钥或官方远程 MCP 的受限 API key，再在 Harness 中配置；所有真实支付写操作必须由用户确认。',
            checks: ['测试环境优先', '密钥使用最小权限和独立轮换', '生产写操作不交给自动工作流'],
            source: 'Stripe 官方 AI 开源项目',
            license: 'MIT',
            repositoryUrl: 'https://github.com/stripe/ai',
        },
    }),
    repoAbility({
        id: 'shopify-ai-toolkit',
        title: 'Shopify/Shopify-AI-Toolkit',
        outcome: '参考 Shopify 官方的 Agent、插件和电商工作流集成方式。',
        summary: '适合零售、电商和 Shopify 开发；优先从 Storefront MCP 和只读店铺数据开始。',
        industryIds: ['retail'],
        kindIds: ['coding', 'agents', 'data-analysis'],
        collectionIds: [],
        aliases: ['Shopify AI Toolkit', 'Shopify', '电商 Agent', 'Storefront MCP'],
        examples: ['查询店铺商品信息', '为 Shopify 做一个客服 Agent'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'mcp',
        popularity: 'GitHub 约 504 星；Shopify 官方项目',
        implementation: {
            extensionTypes: ['plugin', 'skill'],
            goal: '请参考 Shopify 官方 AI Toolkit 和 Storefront MCP，帮我设计一个只读电商助手连接。先说明店铺、商品、订单和客户数据的权限差异，不自动改价、下单或修改库存。',
            addMethod: '先连接公开 Storefront 或测试店铺；只有明确需要管理端数据时，才另行配置最小权限并做单项验证。',
            checks: ['区分 Storefront 和 Admin 权限', '客户和订单数据默认不读取', '任何写操作前显示对象、字段和影响范围'],
            source: 'Shopify 官方 AI Toolkit / Storefront MCP 文档',
            license: 'MIT',
            repositoryUrl: 'https://github.com/Shopify/Shopify-AI-Toolkit',
        },
    }),
    repoAbility({
        id: 'openbb-finance',
        title: 'OpenBB-finance/OpenBB',
        outcome: '为金融研究、行情分析和数据工作流提供一个开源数据平台。',
        summary: '高星金融数据平台，适合做研究辅助，不应被包装成自动交易或投资建议。',
        industryIds: ['financial-services'],
        kindIds: ['data-analysis', 'research'],
        collectionIds: [],
        aliases: ['OpenBB', '金融数据', '行情分析', '量化研究'],
        examples: ['整理一组公开市场数据', '比较几个公司的公开指标'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'project-tool',
        popularity: 'GitHub 约 71.9K 星',
        implementation: {
            extensionTypes: ['plugin', 'skill'],
            goal: '请参考 OpenBB 的公开数据平台，帮我设计一个只读金融研究工作流。先列数据来源、时效、许可证和计算方法，不生成自动交易指令。',
            addMethod: '在隔离项目中安装和验证 OpenBB，再让 Harness 调用固定的数据查询脚本；输出必须标注数据日期和非投资建议说明。',
            checks: ['每项数据标注时间和来源', '区分事实、计算和推断', '不执行真实交易或资金操作'],
            source: 'OpenBB 开源金融数据平台',
            license: 'Other；按具体组件核验',
            repositoryUrl: 'https://github.com/OpenBB-finance/OpenBB',
        },
    }),
    repoAbility({
        id: 'future-house-paper-qa',
        title: 'Future-House/paper-qa',
        outcome: '基于科学论文和文档回答问题，并给出引用。',
        summary: '适合生命科学、医疗研究和教育资料整理；建议先接本地文档或公开论文。',
        industryIds: ['healthcare', 'life-sciences', 'education'],
        kindIds: ['research', 'data-analysis'],
        collectionIds: [],
        aliases: ['PaperQA', '论文问答', '科学文献', '引用'],
        examples: ['比较几篇论文的结论', '为研究摘要补充引用'],
        ecosystem: 'vendor',
        trust: 'maintainer',
        compatibility: 'project-tool',
        popularity: 'GitHub 约 9K 星',
        implementation: {
            extensionTypes: ['plugin', 'skill'],
            goal: '请参考 PaperQA，为我的公开论文或本地文档设计一个带引用的研究流程。先说明文档来源、版本、检索范围和无法确认的内容，不替代医生或研究者判断。',
            addMethod: '先在隔离目录安装并用少量公开论文验证，再让 Harness 通过项目级命令或 MCP 调用；每个结论保留文档引用。',
            checks: ['引用必须能回到原文', '区分论文结论和模型归纳', '医疗问题显示专业复核提示'],
            source: 'Future House 开源科学文档问答项目',
            license: 'Apache-2.0',
            repositoryUrl: 'https://github.com/Future-House/paper-qa',
        },
    }),
    repoAbility({
        id: 'google-hcls-mcp-servers',
        title: 'GoogleCloudPlatform/hcls-mcp-servers',
        outcome: '连接 NIH、FDA、CMS、NLM 等公开健康数据源做检索。',
        summary: 'Google Cloud 公开健康与生命科学数据 MCP 集合；默认只推荐公开数据研究。',
        industryIds: ['healthcare', 'life-sciences', 'government'],
        kindIds: ['research', 'data-analysis'],
        collectionIds: [],
        aliases: ['HCLS MCP', 'NIH', 'FDA', 'CMS', 'NLM', '公共健康数据'],
        examples: ['查公开健康数据', '比较 FDA 或 NIH 的公开资料'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'mcp',
        popularity: 'GitHub 星数较少但为 Google Cloud 官方公开数据集合',
        implementation: {
            extensionTypes: ['plugin'],
            goal: '请阅读 Google HCLS MCP Servers，帮我配置一个只读公开健康数据研究连接。先列出数据源、使用条款、更新时间和医学复核边界。',
            addMethod: '只连接公开数据 MCP；不要配置患者数据、医疗机构内部系统或任何写操作。',
            checks: ['来源、更新时间和使用条款可追溯', '不读取个人健康信息', '结论标注为资料研究，不提供诊断或治疗建议'],
            source: 'Google Cloud 官方公开健康数据 MCP 集合',
            license: 'Apache-2.0',
            repositoryUrl: 'https://github.com/GoogleCloudPlatform/hcls-mcp-servers',
        },
    }),
    repoAbility({
        id: 'getsentry-sentry-mcp',
        title: 'getsentry/sentry-mcp',
        outcome: '让 Harness 读取错误、事件和性能问题，辅助定位真实故障。',
        summary: 'Sentry 官方 MCP 项目；适合程序员团队排查线上问题，但生产数据权限要严格限制。',
        industryIds: ['programmer', 'retail', 'financial-services'],
        kindIds: ['coding', 'data-analysis', 'agents'],
        collectionIds: [],
        aliases: ['Sentry MCP', '错误监控', '异常排查', '性能问题'],
        examples: ['找出最近一次崩溃原因', '比较一个版本前后的错误'],
        ecosystem: 'vendor',
        trust: 'vendor-official',
        compatibility: 'mcp',
        popularity: 'GitHub 约 818 星；Sentry 官方项目',
        implementation: {
            extensionTypes: ['plugin'],
            goal: '请按 Sentry 官方 MCP 和 Harness MCP Client 机制设计一个只读错误分析连接。先限制组织、项目和时间范围，不自动修改 issue 或部署。',
            addMethod: '先用测试项目或只读 token 配置，验证查询一个错误事件；生产写操作和部署操作保持关闭。',
            checks: ['token 最小权限', '日志中不暴露用户隐私或密钥', '输出事件链接、时间和版本号'],
            source: 'Sentry 官方 MCP Server',
            license: 'Other；按仓库和服务条款核验',
            repositoryUrl: 'https://github.com/getsentry/sentry-mcp',
        },
    }),
    repoAbility({
        id: 'anionex-dsh-vision-toolkit',
        title: 'Anionex/dsh-vision-toolkit',
        outcome: '给 DeepSeek Harness 增加图片问答、长截图 OCR、UI 还原和像素对比。',
        summary: 'DeepSeek Harness 原生社区插件，适合我们的鲸鱼主题、界面截图和视觉调试场景。',
        industryIds: ['programmer', 'retail', 'education'],
        kindIds: ['coding', 'data-analysis', 'content-creation'],
        collectionIds: [],
        aliases: ['DSH Vision Toolkit', 'OCR', '图片问答', 'UI 还原', '截图对比'],
        examples: ['从截图还原一个页面', '识别一张长截图里的文字'],
        ecosystem: 'community',
        trust: 'community-reviewed',
        compatibility: 'native',
        popularity: 'DeepSeek Harness 原生项目；GitHub 约 487 星',
        implementation: {
            extensionTypes: ['plugin', 'ui-extension'],
            goal: '请阅读 DSH Vision Toolkit 的版本和权限说明，确认它与当前 DeepSeek Harness 版本兼容后，再设计一个最小视觉能力安装方案。先测试 OCR 或图片问答，不自动修改 UI。',
            addMethod: '打开仓库 README 核对版本和安装方式；在 Creator Mode 中先审计插件包和权限，再由用户确认安装，最后做一张本地截图验证。',
            checks: ['固定版本并记录来源 commit', '图片数据处理范围透明', '提供停止插件、删除配置和回滚方法'],
            source: 'DeepSeek Harness 原生社区插件',
            license: 'MIT',
            repositoryUrl: 'https://github.com/Anionex/dsh-vision-toolkit',
        },
    }),
    repoAbility({
        id: 'dsh-plugin-audit-community',
        title: 'jkrandom-sudo/dsh-plugin-audit',
        outcome: '研究如何对 DeepSeek Harness 插件做静态风险检查和安装前审计。',
        summary: '社区实验项目，星数不高，但方向正好对应 Harness 自由扩展的安全痛点。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'government'],
        kindIds: ['coding', 'agents'],
        collectionIds: [],
        aliases: ['DSH 插件审计', '静态审计', '插件风险'],
        examples: ['检查一个插件有没有危险脚本', '安装前列出网络和文件权限'],
        ecosystem: 'community',
        trust: 'experimental',
        compatibility: 'native',
        popularity: '社区实验项目；GitHub 约 4 星，不作为默认信任依据',
        implementation: {
            extensionTypes: ['plugin', 'workflow'],
            goal: '请把 dsh-plugin-audit 当作实验参考，先审计其代码、许可证和覆盖范围，再设计一个不会替代人工确认的 Harness 插件审计流程。',
            addMethod: '只在隔离项目中阅读和测试；没有完成代码审计前，不要把它加入正式用户配置。',
            checks: ['明确它能检查和不能检查什么', '不把静态审计当作绝对安全保证', '审计失败时默认不安装'],
            source: 'DeepSeek Harness 社区实验项目',
            license: '以仓库当前声明为准',
            repositoryUrl: 'https://github.com/jkrandom-sudo/dsh-plugin-audit',
        },
    }),
    repoAbility({
        id: 'dsh-eval-harness',
        title: 'BiBoyang/dsh-eval-harness',
        outcome: '给 DSH 插件做回归测试和能力验证，避免更新后悄悄失效。',
        summary: '社区实验项目，适合做我们以后维护能力 Hub 的测试思路参考。',
        industryIds: ['programmer'],
        kindIds: ['coding', 'data-analysis'],
        collectionIds: [],
        aliases: ['DSH Eval Harness', '插件回归', '能力评测', '回归测试'],
        examples: ['验证一个插件升级后还可用', '为自定义 Skill 写验收任务'],
        ecosystem: 'community',
        trust: 'experimental',
        compatibility: 'native',
        popularity: '社区实验项目；GitHub 约 5 星',
        implementation: {
            extensionTypes: ['workflow', 'plugin'],
            goal: '请阅读 dsh-eval-harness 的公开说明，帮我为一个 Harness Skill 或插件设计最小回归测试：输入、预期工具、文件变化、权限和失败标准。',
            addMethod: '先对我们自己的 Creator Center 或一个本地 Skill 做测试，不连接生产服务；把验收任务写成可重复的本地测试。',
            checks: ['每次升级前后跑同一组任务', '记录工具调用和文件差异', '失败时保留上一版本并提供回滚'],
            source: 'DeepSeek Harness 社区实验项目',
            license: '以仓库当前声明为准',
            repositoryUrl: 'https://github.com/BiBoyang/dsh-eval-harness',
        },
    }),
    repoAbility({
        id: 'anthropic-skills',
        title: 'anthropics/skills',
        outcome: '参考 Anthropic 公开的文档、办公和创作类 Skill 组织方式。',
        summary: 'GitHub 高星 Skill 仓库，但仓库没有统一许可证结论；只作为参考集合，逐个 Skill 核验后再使用。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'life-sciences', 'retail', 'education'],
        kindIds: ['content-creation', 'research', 'data-analysis'],
        collectionIds: [],
        aliases: ['Anthropic Skills', '文档 Skill', '办公 Skill', '公开 Skill 集合'],
        examples: ['参考一个 PDF 处理 Skill', '把文档工作流程整理成自己的 Skill'],
        ecosystem: 'vendor',
        trust: 'experimental',
        compatibility: 'skill-copy',
        popularity: 'GitHub 约 169K 星；许可证需按子目录核验',
        implementation: {
            extensionTypes: ['skill'],
            goal: '请只阅读 anthropics/skills 中我指定的子目录，先检查该子目录的许可证、依赖和文件范围，再把思路改写成 DeepSeek Harness 的一层 Skill。不要默认复制整仓库。',
            addMethod: '打开具体 Skill 的 GitHub 目录，逐项核对许可证和 SKILL.md；确认后再让 Creator Mode 生成用户自己的版本。',
            checks: ['每个子 Skill 单独核验许可证', '不把 Anthropic 专属工具假设为 Harness 工具', '删除无法解释的远程脚本和隐式网络访问'],
            source: '高星开源 Skill 参考仓库',
            license: '仓库无统一许可证结论；逐子目录核验',
            repositoryUrl: 'https://github.com/anthropics/skills',
        },
    }),
    repoAbility({
        id: 'modelcontextprotocol-servers',
        title: 'modelcontextprotocol/servers',
        outcome: '浏览 MCP 官方参考服务器，寻找适合自己工作流的工具连接。',
        summary: '高星参考集合，不是所有服务器都适合生产或直接接入 Harness；卡片只提供学习和筛选入口。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'retail', 'education'],
        kindIds: ['agents', 'research', 'data-analysis'],
        collectionIds: [],
        aliases: ['MCP Servers', 'MCP 参考服务器', '工具连接集合'],
        examples: ['查找一个适合自己的 MCP', '比较不同 MCP 的权限范围'],
        ecosystem: 'vendor',
        trust: 'experimental',
        compatibility: 'mcp',
        popularity: 'GitHub 约 89.6K 星；参考集合，逐项目核验',
        implementation: {
            extensionTypes: ['plugin'],
            goal: '请从 modelcontextprotocol/servers 中挑选一个具体服务器，先核验维护状态、许可证、权限和数据流，再按 DeepSeek Harness MCP Client 机制设计连接。不要整仓库安装。',
            addMethod: '从集合中进入具体服务器目录，再回到 Creator Mode 生成一个最小 MCP 配置；没有明确许可证、维护状态或回滚方式时不要添加。',
            checks: ['具体服务器逐项核验', '优先只读和本地测试', '不把参考实现当成生产级安全保证'],
            source: 'MCP 官方参考服务器集合',
            license: 'Other；按具体服务器核验',
            repositoryUrl: 'https://github.com/modelcontextprotocol/servers',
        },
    }),
    repoAbility({
        id: 'browser-use',
        title: 'browser-use/browser-use',
        outcome: '研究如何让 AI 使用浏览器完成多步骤任务。',
        summary: '高知名度浏览器 Agent 项目；在 Harness 中建议优先采用 Playwright MCP，避免重复引入另一套浏览器运行时。',
        industryIds: ['programmer', 'retail', 'education'],
        kindIds: ['agents', 'research'],
        collectionIds: [],
        aliases: ['browser-use', '浏览器 Agent', '网页任务'],
        examples: ['比较不同浏览器 Agent 的设计', '给网页自动化选择技术方案'],
        ecosystem: 'community',
        trust: 'community-reviewed',
        compatibility: 'manual-adapter',
        popularity: 'GitHub 高星浏览器 Agent 项目；需按当前版本核验',
        implementation: {
            extensionTypes: ['plugin', 'workflow'],
            goal: '请比较 browser-use 与 Microsoft Playwright MCP，结合当前 DeepSeek Harness 选择最简单、可回滚的浏览器方案。不要同时安装两套浏览器 Agent。',
            addMethod: '优先使用 Playwright MCP；只有明确需要 browser-use 独有能力时，才在隔离项目中研究适配。',
            checks: ['公开页面和测试站点优先', '不绕过权限、验证码或反爬措施', '明确浏览器进程和用户数据目录的清理方式'],
            source: '高知名度开源浏览器 Agent 项目',
            license: '以仓库当前声明为准',
            repositoryUrl: 'https://github.com/browser-use/browser-use',
        },
    }),
    shortAbility({
        id: 'piolium', title: '@vigolium/piolium',
        outcome: '把多阶段安全审计拆给专门的子 Agent，并汇总成可复核结果。',
        summary: 'Pi 目录使用量靠前的安全审计扩展；适合研究 Harness 的审计工作流，不建议直接安装。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'government'], kindIds: ['agents', 'coding'],
        aliases: ['piolium', '安全审计', 'DevSecOps', '多阶段审计'], examples: ['审计一个插件仓库', '检查代码和依赖风险'],
        ecosystem: 'pi', trust: 'maintainer', compatibility: 'manual-adapter', popularity: 'Pi 目录约 231.2K 月下载；GitHub 约 119 星',
        extensionTypes: ['plugin', 'workflow'],
        goal: '请研究 piolium 的安全审计分阶段思路，结合 Harness 官方 Tool、Workflow 和审批机制，先做只读审计方案。不要把 Pi 扩展直接安装到 Harness。',
        addMethod: '让 Creator Mode 先列审计阶段、子 Agent 权限、并发和成本，再用一个本地测试仓库验证。',
        checks: ['审计 Agent 不得拥有生产写权限', '结果保留证据和失败项', '并发、预算和取消条件可配置'], source: 'Pi 官方 Package Catalog / 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/vigolium/piolium',
    }),
    shortAbility({
        id: 'pi-context', title: 'ttttmr/pi-context',
        outcome: '帮助 Agent 管理长任务中的上下文、压缩和任务信息。',
        summary: 'Pi 的上下文管理 Skill；适合作为 Harness 长任务稳定性参考，需用评测验证信息有没有丢。',
        industryIds: ['programmer', 'education'], kindIds: ['agents', 'coding'],
        aliases: ['pi-context', '上下文管理', '长任务'], examples: ['减少长对话失忆', '保存任务关键约束'],
        ecosystem: 'pi', trust: 'maintainer', compatibility: 'manual-adapter', popularity: 'Pi 目录约 3.9K 月下载；GitHub 约 274 星',
        extensionTypes: ['skill', 'workflow'],
        goal: '请对比 pi-context 与 DeepSeek Harness 的上下文压缩、Session 和 Persistence 能力，只有确认存在缺口时才设计补充 Skill。',
        addMethod: '先用三条真实长任务做前后对照，再决定写入用户 Skill 或 preset；不要重复启用两个上下文管理器。',
        checks: ['关键约束在压缩后仍可追溯', '不隐藏地改写用户目标', '失败时可以回看原始会话'], source: 'Pi 官方 Package Catalog / 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/ttttmr/pi-context',
    }),
    shortAbility({
        id: 'pi-prompt-template-model', title: 'nicobailon/pi-prompt-template-model',
        outcome: '按 Prompt 模板的元信息选择模型，帮助多模型工作流做显式路由。',
        summary: 'Pi 目录中使用量较高的 Prompt/模型路由扩展；需要把模型切换和成本边界做成可见设置。',
        industryIds: ['programmer', 'financial-services', 'retail'], kindIds: ['agents', 'coding'],
        aliases: ['模型路由', 'Prompt 模板', '多模型', '成本控制'], examples: ['复杂任务用强模型，简单任务用快模型'],
        ecosystem: 'pi', trust: 'maintainer', compatibility: 'manual-adapter', popularity: 'Pi 目录约 13.8K 月下载；GitHub 约 301 星',
        extensionTypes: ['agent-preset', 'skill'],
        goal: '请参考 pi-prompt-template-model，设计一个 DeepSeek Harness 的显式模型路由规则。模型、费用和权限变化必须显示并由用户确认。',
        addMethod: '先做用户级 preset 规则，不自动切换生产模型；用三种任务验证路由和费用提示。',
        checks: ['模型白名单可见', '切换时说明费用和能力差异', '路由失败时回退到用户选择的模型'], source: 'Pi 官方 Package Catalog / 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/nicobailon/pi-prompt-template-model',
    }),
    shortAbility({
        id: 'pi-llm-wiki', title: 'zosmaai/pi-llm-wiki',
        outcome: '把 URL、PDF 和 Markdown 资料整理成可检索的个人 LLM Wiki。',
        summary: '适合把我们的研究资料、产品知识和运营经验沉淀成长期知识资产。',
        industryIds: ['programmer', 'retail', 'education', 'life-sciences'], kindIds: ['research', 'content-creation'],
        aliases: ['LLM Wiki', '知识库', '资料沉淀', '可检索笔记'], examples: ['把竞品资料整理成知识库', '让 AI 搜索过去的研究'],
        ecosystem: 'pi', trust: 'maintainer', compatibility: 'manual-adapter', popularity: 'Pi 目录约 4.7K 月下载；GitHub 约 504 星',
        extensionTypes: ['skill', 'plugin'],
        goal: '请参考 pi-llm-wiki 的资料沉淀思路，为 DeepSeek Harness 设计一个可查看、可导出、可清空的知识库方案。先做本地公开资料，不保存密钥和敏感信息。',
        addMethod: '先选一个本地资料目录，用 MarkItDown 或文档工具转换，再让 Harness 生成索引和检索 Skill。',
        checks: ['每条知识保留来源和日期', '错误摘要可删除和重建', '敏感文件默认不进入索引'], source: 'Pi 官方 Package Catalog / 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/zosmaai/pi-llm-wiki',
    }),
    shortAbility({
        id: 'rpiv-pi', title: 'juicesharp/rpiv-mono',
        outcome: '参考契约型 Skill、子 Agent 和验证门组成完整研发流程。',
        summary: 'Pi 生态中较完整的研发工作流集合，适合拆解借鉴，不建议整包移植。',
        industryIds: ['programmer'], kindIds: ['coding', 'agents'], aliases: ['rpiv', '契约型 Skill', '研发流程'], examples: ['把需求变成可验收任务', '增加实现后的质量门'],
        ecosystem: 'pi', trust: 'maintainer', compatibility: 'manual-adapter', popularity: 'Pi 目录约 4.1K 月下载；GitHub 约 621 星（monorepo）',
        extensionTypes: ['skill', 'workflow'],
        goal: '请研究 rpiv 的发现、设计、实现、验证和审查分层，只抽取对 DeepSeek Harness 有价值的规则，避免重复已有 Plan、Workflow 和 Subagent。',
        addMethod: '先拆成单个 Skill 或验收清单，在本地项目验证后再加入用户 preset。',
        checks: ['每个阶段有明确输入输出', '失败不能直接标记完成', '不引入隐藏的自动提交或外部写操作'], source: 'Pi 官方 Package Catalog / 维护者 monorepo', license: 'MIT', repositoryUrl: 'https://github.com/juicesharp/rpiv-mono',
    }),
    shortAbility({
        id: 'bigpowers', title: 'danielvm-git/bigpowers',
        outcome: '提供一批工程方法论 Skill，帮助 Agent 按流程完成软件开发。',
        summary: '数量较多的社区 Skill 集合；适合挑选单项规则，不建议一次性全部启用。',
        industryIds: ['programmer'], kindIds: ['coding'], aliases: ['bigpowers', '工程 Skill 集合'], examples: ['找一个代码审查 Skill', '给团队补充开发规范'],
        ecosystem: 'pi', trust: 'maintainer', compatibility: 'manual-adapter', popularity: 'Pi 目录约 15.9K 月下载；GitHub 约 142 星',
        extensionTypes: ['skill'],
        goal: '请从 bigpowers 中挑选一个与当前任务直接相关的 Skill，先解释它和 Harness 已有能力的重叠，再决定是否转写。不要整包加载。',
        addMethod: '逐个查看 SKILL.md 和许可证，把需要的单项 Skill 放进 Harness 一层 Skill 目录。',
        checks: ['单项启用、单项验证', '控制上下文长度', '冲突规则以项目约定为准并明确记录'], source: 'Pi 官方 Package Catalog / 社区 Skill 集合', license: 'MIT', repositoryUrl: 'https://github.com/danielvm-git/bigpowers',
    }),
    shortAbility({
        id: 'superpowers-zh', title: 'jnMetaCode/superpowers-zh',
        outcome: '提供中文开发流程 Skill，帮助中文用户理解规划、测试和验证。',
        summary: 'Superpowers 的社区中文增强版，适合做中文教学入口，不等于 obra 官方版本。',
        industryIds: ['programmer', 'education'], kindIds: ['coding', 'content-creation'], aliases: ['superpowers 中文', '中文 Skill', '研发教学'], examples: ['用中文学习 TDD 流程', '给团队做开发流程培训'],
        ecosystem: 'community', trust: 'community-reviewed', compatibility: 'skill-copy', popularity: 'Pi 目录约 9.2K 月下载；GitHub 约 7.7K 星',
        extensionTypes: ['skill'],
        goal: '请比较 superpowers-zh 与 obra/superpowers 的版本、许可证和内容差异，选择一项中文 Skill 转成 Harness 适配版。',
        addMethod: '先打开两个仓库核对来源，再只复制确认过的 Skill；不把社区中文增强版标成官方。',
        checks: ['区分官方上游和社区翻译', '检查提示词是否适合当前工具名', '保留原仓库和版本信息'], source: 'Pi 目录中的社区中文 Skill 集合', license: 'MIT', repositoryUrl: 'https://github.com/jnMetaCode/superpowers-zh',
    }),
    shortAbility({
        id: 'dsh-plugin-template', title: 'omdsh-dev/plugin-template',
        outcome: '用一个可构建、可测试、可发布的模板开始写 DSH 原生插件。',
        summary: '社区插件脚手架，适合学习 dsh.bundle、cordis.patch.yml、测试和 CI 的组合。',
        industryIds: ['programmer'], kindIds: ['coding'], aliases: ['DSH 插件模板', 'Cordis 模板', 'Bundle'], examples: ['从零写一个工具插件', '给自己的插件加测试'],
        ecosystem: 'community', trust: 'community-reviewed', compatibility: 'native', popularity: '社区项目；GitHub 约 7 星',
        extensionTypes: ['plugin'],
        goal: '请阅读 DSH plugin-template，说明它如何构建、测试和打包；再为我的需求生成一个最小 Cordis Plugin，不复制不必要的模板功能。',
        addMethod: '先在独立目录复制模板并跑通测试，再把业务工具替换进去；完成后固定版本并记录回滚。',
        checks: ['插件退出时清理资源', '测试工具 Schema、错误和取消', '构建脚本和权限先审查'], source: 'DeepSeek Harness 社区插件模板', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/omdsh-dev/plugin-template',
    }),
    shortAbility({
        id: 'awesome-dsh-plugin', title: 'awesome-dsh-plugin/awesome-dsh-plugin',
        outcome: '按 UI、模型、Skill、Memory、Workflow 和 MCP 发现 DSH 社区项目。',
        summary: '社区索引，不是官方认证清单；适合做发现入口，不能直接把列表当作安全推荐。',
        industryIds: ['programmer', 'retail', 'education'], kindIds: ['agents', 'coding', 'research'], aliases: ['Awesome DSH Plugin', 'DSH 插件索引', '社区目录'], examples: ['寻找一个记忆插件', '按类别查看 DSH 项目'],
        ecosystem: 'community', trust: 'experimental', compatibility: 'manual-adapter', popularity: '社区索引；GitHub 约 3.6K 星',
        extensionTypes: ['skill'],
        goal: '请从 awesome-dsh-plugin 选择一个具体仓库，先核验许可证、维护状态、版本和权限，再决定是否加入能力中心推荐，不把索引本身当作安装授权。',
        addMethod: '点击具体项目后回到能力中心详情页做二次审核；不直接执行索引中的安装命令。',
        checks: ['来源项目逐一核验', '明确官方/社区/实验标签', '不展示没有许可证或已失效的项目'], source: 'DeepSeek Harness 社区项目索引', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/awesome-dsh-plugin/awesome-dsh-plugin',
    }),
    shortAbility({
        id: 'dsh-market', title: 'dsh-market/dsh-market',
        outcome: '研究社区市场如何搜索、安装、更新和卸载 DSH 插件。',
        summary: '社区插件市场，不是 DeepSeek 官方市场；适合作为“发现工具”卡片，不进入默认安装。',
        industryIds: ['programmer', 'retail'], kindIds: ['agents', 'coding'], aliases: ['DSH Market', '插件市场', '搜索插件'], examples: ['浏览社区插件', '查看插件安装和更新流程'],
        ecosystem: 'community', trust: 'experimental', compatibility: 'manual-adapter', popularity: '社区项目；GitHub 约 375 星',
        extensionTypes: ['plugin', 'ui-extension'],
        goal: '请阅读 dsh-market 的市场和插件管理实现，先说明它与官方 Harness 插件机制的差异、代码执行和更新风险，不直接安装第三方插件。',
        addMethod: '只打开仓库和界面了解目录设计；正式添加仍走本能力中心的来源、许可证、权限和回滚检查。',
        checks: ['明确不是官方市场', '安装前固定版本并审计', '更新失败保留上一版本'], source: 'DeepSeek Harness 社区插件市场', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/dsh-market/dsh-market',
    }),
    shortAbility({
        id: 'dsh-find-plugin', title: 'awesome-dsh-plugin/dsh-find-plugin',
        outcome: '让 Agent 从 GitHub Topic 和社区索引中寻找 DSH 插件。',
        summary: '社区搜索工具，解决“我不知道该搜什么插件”的痛点，但搜索结果仍需人工核验。',
        industryIds: ['programmer', 'retail', 'education'], kindIds: ['research', 'agents'], aliases: ['Find DSH Plugin', '插件搜索', 'GitHub Topic'], examples: ['帮我找一个文档插件', '搜索 DSH 的视觉扩展'],
        ecosystem: 'community', trust: 'experimental', compatibility: 'manual-adapter', popularity: '社区项目；GitHub 约 33 星',
        extensionTypes: ['plugin', 'skill'],
        goal: '请参考 dsh-find-plugin 的搜索思路，设计一个只返回来源、许可证、版本和风险信息的能力中心发现流程，不自动安装搜索结果。',
        addMethod: '把搜索结果作为待审核候选，必须进入详情页完成来源核验后才能推荐。',
        checks: ['不把排序当作质量', '过滤缺许可证和无维护项目', '保存搜索时间和原始链接'], source: 'DeepSeek Harness 社区搜索工具', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/awesome-dsh-plugin/dsh-find-plugin',
    }),
    shortAbility({
        id: 'dsh-continual-evolve', title: 'ZK-Andy/dsh-continual-evolve',
        outcome: '研究 Skill、Memory、Prompt、Trajectory 的版本化、审查、评测和回滚。',
        summary: '很贴近“Harness 自己让自己变强”的营销方向，但会改写能力和记忆，必须隔离并人工审核。',
        industryIds: ['programmer', 'education'], kindIds: ['agents', 'coding'], aliases: ['持续进化', '记忆治理', '轨迹评测', '自我改进'], examples: ['让 Harness 复盘失败任务', '给 Skill 建立版本和评测'],
        ecosystem: 'community', trust: 'experimental', compatibility: 'native', popularity: '社区实验项目；GitHub 约 6 星',
        extensionTypes: ['workflow', 'plugin', 'skill'],
        goal: '请阅读 dsh-continual-evolve，先画出它修改 Prompt、Memory、Skill 和 Trajectory 的范围，再设计一个只读复盘和人工批准的最小版本。',
        addMethod: '只在隔离 Profile 和测试项目中试用；任何写入长期记忆或 Skill 的动作必须先生成 diff 并等待用户确认。',
        checks: ['所有变化可查看、比较和回滚', '不能自动扩大权限', '评测失败时保留上一版本'], source: 'DeepSeek Harness 社区实验项目', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/ZK-Andy/dsh-continual-evolve',
    }),
    shortAbility({
        id: 'dsh-skill-pack-security', title: 'PerryLink/dsh-skill-pack-security',
        outcome: '用 Skill 指导密钥扫描、依赖审计、供应链和 Prompt Injection 检查。',
        summary: '社区安全 Skill Pack，适合做能力中心安全教学样例，不等于强制安全边界。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'government'], kindIds: ['coding', 'agents'], aliases: ['安全 Skill', '密钥扫描', '供应链审查', 'Prompt Injection'], examples: ['审查一个准备安装的插件', '找出仓库里的密钥风险'],
        ecosystem: 'community', trust: 'experimental', compatibility: 'skill-copy', popularity: '社区项目；GitHub 约 2 星',
        extensionTypes: ['skill'],
        goal: '请阅读 dsh-skill-pack-security 中指定的安全 Skill，核验命令和许可证后，生成一个只做审查、不自动修复或删除文件的 Harness Skill。',
        addMethod: '先在测试仓库运行只读扫描，确认命令和误报范围，再复制单项 Skill 到用户目录。',
        checks: ['扫描结果需人工复核', '不把 Skill 当作沙箱或权限系统', '密钥命中时不在报告中回显完整内容'], source: 'DeepSeek Harness 社区安全 Skill Pack', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/PerryLink/dsh-skill-pack-security',
    }),
    shortAbility({
        id: 'shopline-ai-toolkit-dsh', title: 'lunw/shopline-ai-toolkit-dsh',
        outcome: '参考把电商 Skill、MCP、OAuth 和 Bundle 组合成行业域包。',
        summary: '社区 SHOPLINE 示例，适合我们的跨境电商方向；默认只做商品和 Listing 的只读场景。',
        industryIds: ['retail'], kindIds: ['agents', 'data-analysis', 'coding'], aliases: ['SHOPLINE', '电商域包', '商品管理', 'Listing'], examples: ['整理商品信息', '研究一个电商 API 域包'],
        ecosystem: 'community', trust: 'experimental', compatibility: 'native', popularity: '社区项目；GitHub 约 2 星',
        extensionTypes: ['plugin', 'skill'],
        goal: '请阅读 shopline-ai-toolkit-dsh，抽取 Skill、MCP、Bundle 和 OAuth 的组织方式，先设计只读商品/Listing 查询，不触碰真实订单、库存和客户数据。',
        addMethod: '在测试店铺和独立 Profile 中验证；任何写操作必须拆成单独教程并逐次确认。',
        checks: ['店铺 Token 最小权限', '默认只读', '显示请求对象、字段和可能的业务影响'], source: 'DeepSeek Harness 社区电商示例', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/lunw/shopline-ai-toolkit-dsh',
    }),
    shortAbility({
        id: 'dsh-feishu', title: 'xmanrui/dsh-feishu',
        outcome: '研究把飞书机器人、长连接和会话映射接入 DSH 的方式。',
        summary: 'README 明确按 DSH 0.1.0-rc.6 开发的社区样本；项目较新，必须使用测试应用和最小权限。',
        industryIds: ['retail', 'government', 'education'], kindIds: ['agents', 'content-creation'], aliases: ['飞书', 'Lark', '机器人', '消息集成'], examples: ['把通知发到飞书', '从飞书触发一个只读任务'],
        ecosystem: 'community', trust: 'experimental', compatibility: 'native', popularity: '社区项目；README 标注 rc.6，GitHub 星数较低',
        extensionTypes: ['plugin'],
        goal: '请审计 dsh-feishu 的权限、消息流、会话映射和版本要求，先用测试飞书应用做只读通知验证，不发送敏感内容。',
        addMethod: '在隔离 Profile 中安装并填写测试应用配置；验证消息收发和关闭后再考虑加入工作流。',
        checks: ['App Secret 不进入仓库', '限制机器人和群范围', '支持断开、重连和消息审计'], source: 'DeepSeek Harness 社区飞书集成', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/xmanrui/dsh-feishu',
    }),
    shortAbility({
        id: 'dsh-plugin-knowledge-graph', title: 'Luke-Yong/dsh-plugin-knowledge-graph',
        outcome: '把代码结构、引用和依赖关系整理成可查询的知识图谱。',
        summary: '社区早期项目，适合研究 Harness 如何理解大型代码库，不建议作为生产基线。',
        industryIds: ['programmer'], kindIds: ['coding', 'data-analysis'], aliases: ['知识图谱', '代码依赖', '代码结构'], examples: ['查一个函数被谁引用', '了解项目模块关系'],
        ecosystem: 'community', trust: 'experimental', compatibility: 'native', popularity: '社区早期项目；GitHub 约 3 星',
        extensionTypes: ['plugin'],
        goal: '请阅读 dsh-plugin-knowledge-graph，先确认代码解析范围和生成文件，再设计一个只读代码结构查询工具，不修改源代码。',
        addMethod: '在副本项目中构建图谱并检查输出；完成后只把查询工具挂到测试 Profile。',
        checks: ['输入目录由用户指定', '图谱生成不执行项目脚本', '提供重建和删除索引方法'], source: 'DeepSeek Harness 社区插件', license: '以仓库当前声明为准', repositoryUrl: 'https://github.com/Luke-Yong/dsh-plugin-knowledge-graph',
    }),
    shortAbility({
        id: 'docling', title: 'docling-project/docling',
        outcome: '保留表格、版面和结构地解析复杂 PDF 与办公文档。',
        summary: '高星文档解析项目，适合 MarkItDown 无法保留版面时作为进阶工具。',
        industryIds: ['financial-services', 'healthcare', 'life-sciences', 'government', 'education', 'retail'], kindIds: ['research', 'data-analysis'], aliases: ['Docling', '复杂 PDF', '表格识别', '版面解析'], examples: ['解析一份带表格的报告', '从 PDF 保留章节和表格'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 64.8K 星',
        extensionTypes: ['plugin', 'skill'],
        goal: '请比较 Docling 和 MarkItDown，选择一个适合当前文档的解析方式。先处理一份副本，保留页码、表格和来源，不扫描整个磁盘。',
        addMethod: '在隔离 Python 环境中安装，先转换一份公开样本，再让 Harness 调用固定命令。',
        checks: ['原文件只读', '表格和页码缺失时标记', '本地文档不上传第三方服务'], source: '开源文档解析项目', license: 'MIT', repositoryUrl: 'https://github.com/docling-project/docling',
    }),
    shortAbility({
        id: 'paddleocr', title: 'PaddlePaddle/PaddleOCR',
        outcome: '从图片和 PDF 中识字、识表格并提取版面信息。',
        summary: '高星 OCR 项目，适合截图、票据、产品图和多语言资料；需要评估本机资源。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'life-sciences', 'retail', 'government', 'education'], kindIds: ['data-analysis', 'research'], aliases: ['PaddleOCR', 'OCR', '表格识别', '图片文字'], examples: ['识别一张截图', '提取扫描 PDF 表格'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 87.7K 星；PaddlePaddle 官方项目',
        extensionTypes: ['plugin', 'skill'],
        goal: '请评估 PaddleOCR 的本地依赖、模型、语言和许可证，先在一张非敏感图片上做 OCR，再决定是否接入 Harness。',
        addMethod: '在隔离环境安装并固定模型版本；让 Harness 只调用本地 OCR 命令，输出文件由用户指定。',
        checks: ['图片默认不外传', '识别结果标注置信度和人工复核', 'GPU/CPU 依赖和模型大小提前说明'], source: 'PaddlePaddle 官方 OCR 项目', license: 'Apache-2.0', repositoryUrl: 'https://github.com/PaddlePaddle/PaddleOCR',
    }),
    shortAbility({
        id: 'stanford-storm', title: 'stanford-oval/storm',
        outcome: '先检索资料、整理不同观点，再生成带引用的研究报告。',
        summary: 'Stanford OVAL 的研究报告生成项目，适合做调研能力的进阶参考。',
        industryIds: ['financial-services', 'life-sciences', 'government', 'education', 'retail'], kindIds: ['research', 'content-creation'], aliases: ['STORM', '研究报告', '引用报告', '资料综述'], examples: ['做一份行业调研', '比较多个公开观点'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 31K 星；Stanford OVAL 项目',
        extensionTypes: ['plugin', 'workflow'],
        goal: '请参考 STORM 的研究流程，为 DeepSeek Harness 设计一个带来源、观点分歧和事实核验的研究工作流。先使用公开资料，不代替专业判断。',
        addMethod: '在隔离项目运行小主题研究，再把检索、提纲、写作和引用检查拆成可验证步骤。',
        checks: ['关键结论附来源', '区分事实与推断', '来源冲突时保留不同观点'], source: 'Stanford OVAL 开源研究项目', license: 'MIT', repositoryUrl: 'https://github.com/stanford-oval/storm',
    }),
    shortAbility({
        id: 'duckdb', title: 'duckdb/duckdb',
        outcome: '直接分析 CSV、Parquet、JSON 等本地数据文件，不必先搭一套数据库。',
        summary: '高星嵌入式分析数据库，适合电商、财务、运营和研究数据的只读分析。',
        industryIds: ['financial-services', 'retail', 'government', 'education', 'life-sciences'], kindIds: ['data-analysis'], aliases: ['DuckDB', 'CSV 分析', 'Parquet', '本地数据'], examples: ['分析一批订单 CSV', '找出数据中的异常趋势'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 40.3K 星',
        extensionTypes: ['plugin', 'skill'],
        goal: '请用 DuckDB 为我设计一个只读本地数据分析任务：先列文件、字段、SQL 和输出目录，不修改原始数据。',
        addMethod: '在项目级环境中调用 DuckDB CLI 或脚本，让 Harness 生成可复查 SQL 和结果文件。',
        checks: ['原始数据只读', 'SQL 和结果可复现', '敏感字段在输出前脱敏'], source: 'DuckDB 官方开源数据库', license: 'MIT', repositoryUrl: 'https://github.com/duckdb/duckdb',
    }),
    shortAbility({
        id: 'pandas', title: 'pandas-dev/pandas',
        outcome: '清洗、合并和统计分析表格数据。',
        summary: 'Python 数据处理基础设施；作为项目级工具比包装成高权限全局插件更稳妥。',
        industryIds: ['financial-services', 'retail', 'government', 'education', 'life-sciences'], kindIds: ['data-analysis'], aliases: ['pandas', '表格清洗', '数据统计'], examples: ['清洗 Excel 导出的数据', '合并多张表并输出分析'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 49.5K 星；Python 核心生态',
        extensionTypes: ['plugin', 'skill'],
        goal: '请用 pandas 设计一个可复现的数据清洗脚本：先读取样本、展示字段和缺失值，再生成脚本和结果，不覆盖原始文件。',
        addMethod: '在隔离 Python 环境安装，Harness 只调用项目脚本并展示输入输出文件。',
        checks: ['保留原始数据', '记录清洗规则和行数变化', '结果可用第二次运行复现'], source: 'Python 数据处理开源项目', license: 'BSD-3-Clause', repositoryUrl: 'https://github.com/pandas-dev/pandas',
    }),
    shortAbility({
        id: 'composio', title: 'ComposioHQ/composio',
        outcome: '把大量 SaaS 连接器包装成 Agent 可调用工具。',
        summary: '高星连接器平台，适合研究“行业能力包”，但连接器写权限和 OAuth 范围必须逐项限制。',
        industryIds: ['programmer', 'retail', 'financial-services', 'education'], kindIds: ['agents', 'coding'], aliases: ['Composio', 'SaaS 连接器', 'OAuth', '工具生态'], examples: ['连接 Notion、Slack 或 Jira', '给 Agent 加一个 SaaS 工具'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'mcp', popularity: 'GitHub 约 29.7K 星；连接大量 SaaS 工具',
        extensionTypes: ['plugin'],
        goal: '请评估 Composio 与 Harness 官方 MCP Client 的关系，先挑一个只读 SaaS 连接做权限和数据流审计，不要一次性开放全部工具。',
        addMethod: '使用测试 OAuth 和单个连接器，在 Creator Mode 中配置最小权限；写操作必须单独审批。',
        checks: ['每个连接器单独审核', 'OAuth 范围和 token 可撤销', '工具副作用显示给用户'], source: '开源 Agent SaaS 连接器平台', license: 'MIT', repositoryUrl: 'https://github.com/ComposioHQ/composio',
    }),
    shortAbility({
        id: 'mcp-use', title: 'mcp-use/mcp-use',
        outcome: '用 Python 或 TypeScript 快速开发自己的 MCP Server 和 MCP App。',
        summary: '适合想自己给 Harness 做外部工具的人；它是开发框架，不是普通用户直接安装的能力。',
        industryIds: ['programmer', 'retail', 'education'], kindIds: ['coding', 'agents'], aliases: ['mcp-use', 'MCP Server', 'MCP App'], examples: ['给内部 API 写 MCP', '把一个脚本包装成工具'],
        ecosystem: 'community', trust: 'maintainer', compatibility: 'manual-adapter', popularity: 'GitHub 约 10.5K 星',
        extensionTypes: ['plugin'],
        goal: '请参考 mcp-use 的开发方式，结合 DeepSeek Harness 官方 MCP Client，帮我把一个本地只读脚本包装成 MCP Server。先输出 Schema、权限和测试。',
        addMethod: '在独立项目中开发和测试 MCP Server，再让 Harness 连接它；不要直接把开发框架塞进生产 Profile。',
        checks: ['工具 Schema 明确', '输入和输出可验证', '高风险动作默认关闭'], source: '社区 MCP 开发框架', license: 'MIT', repositoryUrl: 'https://github.com/mcp-use/mcp-use',
    }),
    shortAbility({
        id: 'mcp-atlassian', title: 'sooperset/mcp-atlassian',
        outcome: '让 Agent 查询 Jira 和 Confluence，整理项目任务和知识。',
        summary: '社区高星 Atlassian MCP 连接器，适合企业研发和项目协作；写权限需要单独审批。',
        industryIds: ['programmer', 'government', 'education'], kindIds: ['agents', 'research'], aliases: ['Jira', 'Confluence', 'Atlassian MCP', '项目协作'], examples: ['整理一个 Sprint 的任务', '搜索项目文档和 Issue'],
        ecosystem: 'community', trust: 'community-reviewed', compatibility: 'mcp', popularity: 'GitHub 约 5.7K 星',
        extensionTypes: ['plugin'],
        goal: '请审计 mcp-atlassian 的 OAuth、Jira 和 Confluence 权限，先设计只读查询连接，不创建、修改或关闭 Issue。',
        addMethod: '在测试空间配置 OAuth 或 token，通过 Harness MCP Client 只做搜索和读取测试。',
        checks: ['限制站点、项目和空间', '写操作默认关闭', '输出文档和 Issue 链接'], source: '社区 Atlassian MCP 连接器', license: 'MIT', repositoryUrl: 'https://github.com/sooperset/mcp-atlassian',
    }),
    shortAbility({
        id: 'ccxt', title: 'ccxt/ccxt',
        outcome: '用统一接口读取多个交易所的市场数据和 API。',
        summary: '适合金融数据研究，不允许把它包装成自动下单能力或投资决策器。',
        industryIds: ['financial-services'], kindIds: ['data-analysis', 'research'], aliases: ['CCXT', '交易所 API', '市场行情'], examples: ['读取公开行情', '比较多个交易所数据'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 43.6K 星',
        extensionTypes: ['plugin', 'skill'],
        goal: '请使用 CCXT 设计一个只读取市场数据的研究脚本，先说明交易所、时间范围和 API 权限，禁止真实下单和资金操作。',
        addMethod: '在隔离项目中使用公开或只读 API，Harness 只调用数据查询脚本。',
        checks: ['API key 不授予交易权限', '数据标注时间和来源', '禁止任何自动下单或资金转移'], source: '开源交易所 API 统一库', license: 'MIT', repositoryUrl: 'https://github.com/ccxt/ccxt',
    }),
    shortAbility({
        id: 'yfinance', title: 'ranaroussi/yfinance',
        outcome: '获取 Yahoo Finance 的公开市场数据做基础研究。',
        summary: '金融研究常用 Python 工具，适合作为只读数据脚本，不等于实时或完整行情服务。',
        industryIds: ['financial-services', 'education'], kindIds: ['data-analysis', 'research'], aliases: ['yfinance', 'Yahoo Finance', '股票数据'], examples: ['下载一段历史行情', '比较几支股票的指标'],
        ecosystem: 'community', trust: 'community-reviewed', compatibility: 'project-tool', popularity: 'GitHub 约 25K 星',
        extensionTypes: ['plugin', 'skill'],
        goal: '请用 yfinance 生成一个可复现的公开历史数据研究脚本，标注数据日期和使用限制，不给出交易建议。',
        addMethod: '在本地 Python 环境运行查询脚本，Harness 只读取生成的 CSV 和分析结果。',
        checks: ['说明数据延迟和许可', '不把结果当作实时行情', '不执行交易'], source: '社区常用金融数据工具', license: 'Apache-2.0', repositoryUrl: 'https://github.com/ranaroussi/yfinance',
    }),
    shortAbility({
        id: 'synthea', title: 'synthetichealth/synthea',
        outcome: '生成不对应真实患者的仿真病历，用于测试医疗数据流程。',
        summary: '医疗场景的安全测试入口；适合做 Harness 数据分析演示，不能替代真实医疗数据合规。',
        industryIds: ['healthcare', 'life-sciences', 'education'], kindIds: ['data-analysis', 'research'], aliases: ['Synthea', '仿真病历', '医疗测试数据'], examples: ['测试一个 FHIR 数据流程', '演示医疗数据分析'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 3.3K 星；SyntheticHealth 项目',
        extensionTypes: ['plugin', 'skill'],
        goal: '请使用 Synthea 生成仿真医疗数据，设计一个只处理虚拟数据的 Harness 分析示例，不连接真实患者系统。',
        addMethod: '在隔离环境运行数据生成器，确认输出没有真实患者信息后再交给 Harness 分析。',
        checks: ['明确数据为仿真数据', '不连接真实 EHR 或患者接口', '输出中保留数据生成参数'], source: 'SyntheticHealth 开源医疗仿真项目', license: 'Apache-2.0', repositoryUrl: 'https://github.com/synthetichealth/synthea',
    }),
    shortAbility({
        id: 'biopython', title: 'biopython/biopython',
        outcome: '读写序列、GenBank 和 NCBI 等生物信息数据。',
        summary: '生命科学基础库，适合做本地数据处理 Skill 或项目级脚本。',
        industryIds: ['life-sciences', 'education'], kindIds: ['data-analysis', 'research'], aliases: ['Biopython', '生物信息学', '序列分析'], examples: ['读取一批序列文件', '整理 GenBank 数据'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 5.2K 星；官方项目',
        extensionTypes: ['plugin', 'skill'],
        goal: '请用 Biopython 设计一个本地生物数据整理任务，先说明输入格式、数据来源和输出目录，不访问未授权数据源。',
        addMethod: '在隔离 Python 环境调用脚本，Harness 负责解释参数、执行已确认命令和总结结果。',
        checks: ['输入和来源可追溯', '不把研究结果解释成临床结论', '保留原始序列和脚本版本'], source: 'Biopython 开源项目', license: 'Biopython License / BSD-3-Clause 部分文件', repositoryUrl: 'https://github.com/biopython/biopython',
    }),
    shortAbility({
        id: 'openrefine', title: 'OpenRefine/OpenRefine',
        outcome: '清洗、去重、纠正和整理质量较差的表格数据。',
        summary: '适合政府公共数据、电商商品表和运营数据的人工可复核清洗。',
        industryIds: ['government', 'retail', 'financial-services', 'education'], kindIds: ['data-analysis'], aliases: ['OpenRefine', '数据清洗', '去重', '脏数据'], examples: ['清洗商品导出表', '合并和纠正公共数据'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 11.9K 星',
        extensionTypes: ['plugin', 'skill'],
        goal: '请用 OpenRefine 设计一个可预览、可撤销的数据清洗流程：先复制原始文件，再展示每一步变更，不直接覆盖源数据。',
        addMethod: '在本地启动 OpenRefine 或使用项目导出脚本，Harness 负责生成清洗规则和验收报告。',
        checks: ['原始数据只读', '每一步可撤销', '输出行数和字段变化可复核'], source: '成熟开源数据清洗工具', license: 'BSD-3-Clause', repositoryUrl: 'https://github.com/OpenRefine/OpenRefine',
    }),
    shortAbility({
        id: 'jupyterlab', title: 'jupyterlab/jupyterlab',
        outcome: '在 Notebook 中运行实验、数据分析和可复查的教学代码。',
        summary: '适合教育、研究和数据分析；Harness 只生成或运行用户确认的 Notebook。',
        industryIds: ['education', 'life-sciences', 'financial-services', 'retail'], kindIds: ['data-analysis', 'coding'], aliases: ['JupyterLab', 'Notebook', '教学实验', '数据分析'], examples: ['把数据分析做成 Notebook', '给学生生成一个实验模板'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 15.3K 星；Jupyter 官方项目',
        extensionTypes: ['plugin', 'skill'],
        goal: '请为一个本地数据集生成可复查的 Jupyter Notebook：先列输入文件、依赖和输出，再由我确认后运行，不访问外部服务。',
        addMethod: '在独立环境启动 JupyterLab，Harness 生成 Notebook 和运行说明，不把 Notebook 服务器暴露到公网。',
        checks: ['固定依赖和随机种子', 'Notebook 输出可重跑', '关闭服务器并清理临时文件'], source: 'Jupyter 官方开源项目', license: 'BSD-3-Clause', repositoryUrl: 'https://github.com/jupyterlab/jupyterlab',
    }),
    shortAbility({
        id: 'ui-ux-pro-max-skill', title: 'nextlevelbuilder/ui-ux-pro-max-skill',
        outcome: '为网页、App 和后台界面提供可查询的 UI/UX 设计知识库。',
        summary: '包含风格、配色、字体、图表、产品类型和多技术栈规则，适合先确定设计系统再编码。',
        industryIds: ['programmer', 'retail', 'education'], kindIds: ['coding', 'content-creation'], aliases: ['UI UX Pro Max', 'UI 设计 Skill', '设计系统', '配色'], examples: ['给 SaaS 后台选设计方向', '检查移动端 UI 规范'],
        ecosystem: 'community', trust: 'maintainer', compatibility: 'skill-copy', popularity: 'GitHub 约 117.2K 星；2026-08-16 快照',
        extensionTypes: ['skill'],
        goal: '请从 ui-ux-pro-max-skill 中选择与当前产品类型和技术栈匹配的规则，先生成设计方向与 token，再由我确认后实现。不要一次加载整个知识库。',
        addMethod: '先阅读仓库的安装和查询方式，只复制需要的 Skill 与数据文件到用户目录；用一个页面验证检索、设计建议和输出质量。',
        checks: ['只安装需要的 Skill', '设计建议必须对应当前产品和技术栈', '完成后说明更新与删除目录'], source: 'UI/UX Pro Max 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/nextlevelbuilder/ui-ux-pro-max-skill',
    }),
    shortAbility({
        id: 'leonxlnx-taste-skill', title: 'Leonxlnx/taste-skill',
        outcome: '用明确的视觉方向、密度和动效规则减少模板化 AI 前端。',
        summary: '包含 design-taste-frontend、重设计、图生代码和多种视觉风格 Skill，可按单项安装。',
        industryIds: ['programmer', 'retail'], kindIds: ['coding', 'content-creation'], aliases: ['Taste Skill', 'design-taste-frontend', 'gpt-taste', '反 AI 味'], examples: ['重设计一个旧页面', '让 Codex 做更有设计感的前端'],
        ecosystem: 'community', trust: 'maintainer', compatibility: 'skill-copy', popularity: 'GitHub 约 77K 星；2026-08-16 快照',
        extensionTypes: ['skill'],
        goal: '请只选择 Taste Skill 中与当前任务匹配的一项 Skill，说明稳定版和实验版差异，再按现有前端栈执行设计审计或实现。',
        addMethod: '优先安装单项 design-taste-frontend 或 redesign-existing-projects，不整包加载；在一个页面副本上比较启用前后结果。',
        checks: ['单项 Skill 安装', '实验版需明确标记', '不覆盖项目已有设计规范'], source: 'Taste Skill 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/Leonxlnx/taste-skill',
    }),
    shortAbility({
        id: 'pbakaus-impeccable', title: 'pbakaus/impeccable',
        outcome: '为 AI 前端加入初始化、审计、批评、打磨和设计系统提取流程。',
        summary: '提供一套设计 Skill、多个命令和确定性检查规则，覆盖可访问性、响应式、排版与动效。',
        industryIds: ['programmer', 'retail'], kindIds: ['coding'], aliases: ['Impeccable', '前端审计', 'UI 打磨', '设计检查'], examples: ['审计一个后台页面', '发布前检查前端质量'],
        ecosystem: 'community', trust: 'maintainer', compatibility: 'skill-copy', popularity: 'GitHub 约 59.6K 星；2026-08-16 快照',
        extensionTypes: ['skill', 'plugin'],
        goal: '请先用 Impeccable 的只读审计与 critique 思路检查当前页面，列出问题和证据；只有我确认后再执行 polish 或 layout 修改。',
        addMethod: '先核对 Codex/Harness 支持目录和 hook 权限，在测试项目安装；不自动批准 hook，不覆盖真实 Skill 目录。',
        checks: ['Hook 必须人工批准', '先审计再修改', '保留变更清单和卸载方法'], source: 'Impeccable 维护者仓库', license: 'Apache-2.0', repositoryUrl: 'https://github.com/pbakaus/impeccable',
    }),
    shortAbility({
        id: 'emilkowalski-skills', title: 'emilkowalski/skills',
        outcome: '为界面动效、原型和设计工程提供专家级 Skill。',
        summary: '包含动画审查、动效改进、Apple 设计、UI 库选择和原型 Skill，适合精细化前端体验。',
        industryIds: ['programmer', 'retail'], kindIds: ['coding'], aliases: ['Emil Skills', '动画设计', '设计工程', 'prototype'], examples: ['检查页面动效是否自然', '做一个可交互原型'],
        ecosystem: 'community', trust: 'maintainer', compatibility: 'skill-copy', popularity: 'GitHub 约 29.8K 星；2026-08-16 快照',
        extensionTypes: ['skill'],
        goal: '请从 emilkowalski/skills 中选择一个与当前问题直接相关的 Skill，例如 review-animations 或 prototype，先解释适用范围再执行。',
        addMethod: '逐个查看 skills 子目录，只复制选定 Skill；动效修改前先记录当前行为，并尊重 prefers-reduced-motion。',
        checks: ['一次只启用一个目标 Skill', '动效必须支持减少动画', '输出可复查的前后差异'], source: 'Emil Kowalski 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/emilkowalski/skills',
    }),
    shortAbility({
        id: 'vercel-agent-skills', title: 'vercel-labs/agent-skills',
        outcome: '使用 Vercel 官方的 React、Next.js、Web 设计和组件架构 Skill。',
        summary: '包含 React 性能、Web 设计规范、组合模式、React Native 和部署等可单独安装的 Skill。',
        industryIds: ['programmer'], kindIds: ['coding'], aliases: ['Vercel Skills', 'React Best Practices', 'Web Design Guidelines', 'Next.js'], examples: ['审查 React 性能', '检查网页可访问性和 UX'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'skill-copy', popularity: 'GitHub 约 30.1K 星；2026-08-16 快照',
        extensionTypes: ['skill'],
        goal: '请从 Vercel Agent Skills 中选择 react-best-practices、web-design-guidelines 或 composition-patterns 之一，按当前项目版本执行，不混用无关规则。',
        addMethod: '先列出仓库中的 Skill，选择单项后复制到用户目录；React 规则必须先确认当前 React/Next.js 版本。',
        checks: ['单项安装', '框架版本匹配', '性能建议附具体代码位置和验证方法'], source: 'Vercel Labs 官方 Agent Skills 仓库', license: 'MIT（README 声明）', repositoryUrl: 'https://github.com/vercel-labs/agent-skills',
    }),
    shortAbility({
        id: 'vercel-agent-browser', title: 'vercel-labs/agent-browser',
        outcome: '让 Agent 用面向自动化的 CLI 检查网页、React 组件树和 Web Vitals。',
        summary: '适合前端验收、浏览器自动化和性能排查；工具能力强，应限制目标站点和写操作。',
        industryIds: ['programmer'], kindIds: ['coding', 'research', 'agents'], aliases: ['Agent Browser', '浏览器自动化', 'Web Vitals', 'React DevTools'], examples: ['检查页面 LCP 和 CLS', '查看 React 组件树'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 40.7K 星；2026-08-16 快照',
        extensionTypes: ['plugin', 'skill'],
        goal: '请用 agent-browser 对我指定的本地页面做只读检查，先列出准备执行的命令和访问范围，不提交表单、不修改远程数据。',
        addMethod: '在项目级环境安装并固定版本，先打开本地测试页验证 snapshot、vitals 和 React 检查，再决定是否封装为 Harness Skill。',
        checks: ['默认只访问本地或指定 URL', '禁止隐式提交和远程写入', '保存命令、结果与停用方式'], source: 'Vercel Labs 官方浏览器自动化项目', license: 'Apache-2.0', repositoryUrl: 'https://github.com/vercel-labs/agent-browser',
    }),
    shortAbility({
        id: 'github-awesome-copilot', title: 'github/awesome-copilot',
        outcome: '参考 GitHub 官方社区收集的 instructions、agents、skills 和配置。',
        summary: '覆盖开发语言、框架、测试、审查和工作流；适合挑选单项方法，不适合整库启用。',
        industryIds: ['programmer', 'education'], kindIds: ['coding', 'agents'], aliases: ['Awesome Copilot', 'GitHub Copilot Skills', '开发指令'], examples: ['寻找一个测试 Skill', '参考官方社区的代码审查指令'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'manual-adapter', popularity: 'GitHub 约 37.9K 星；2026-08-16 快照',
        extensionTypes: ['skill', 'agent-preset'],
        goal: '请从 awesome-copilot 选择一个与当前项目直接相关的 instruction、agent 或 skill，先核对工具名和许可证，再改写成 Harness 用户能力。',
        addMethod: '只复制选定文件的思路，不整库安装；把 Copilot 专属变量和工具名替换为当前 Harness 实际接口。',
        checks: ['逐项核验来源', '适配 Harness 工具名', '不自动添加 GitHub 写权限'], source: 'GitHub 官方社区资源仓库', license: 'MIT', repositoryUrl: 'https://github.com/github/awesome-copilot',
    }),
    shortAbility({
        id: 'supabase-mcp', title: 'supabase/mcp',
        outcome: '让 Harness 查询 Supabase 项目、数据库和官方文档。',
        summary: 'Supabase 官方 MCP，支持项目范围、只读模式和功能组限制，适合后端开发与排错。',
        industryIds: ['programmer', 'retail', 'financial-services'], kindIds: ['coding', 'data-analysis', 'agents'], aliases: ['Supabase MCP', 'Postgres', '后端数据库'], examples: ['只读检查数据库结构', '查询 Supabase 文档'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'mcp', popularity: 'GitHub 约 2.9K 星；2026-08-16 快照',
        extensionTypes: ['plugin'],
        goal: '请按 Supabase 官方 MCP 文档创建项目级、只读连接，只启用 database 和 docs 等必要 feature；先展示 URL、范围和权限。',
        addMethod: '通过 Harness MCP Client 配置官方服务，优先使用 project_ref 与 read_only=true；密钥由用户自己填写。',
        checks: ['固定到单个项目', '默认 read_only', '不在日志或配置示例中回显密钥'], source: 'Supabase 官方 MCP 仓库', license: 'Apache-2.0', repositoryUrl: 'https://github.com/supabase/mcp',
    }),
    shortAbility({
        id: 'neon-mcp-server', title: 'neondatabase/mcp-server-neon',
        outcome: '连接 Neon 管理 API 和 Postgres 数据库，辅助后端开发。',
        summary: 'Neon 官方 MCP；适合开发环境的项目与分支管理，生产写操作必须单独确认。',
        industryIds: ['programmer', 'financial-services', 'retail'], kindIds: ['coding', 'data-analysis', 'agents'], aliases: ['Neon MCP', 'Postgres MCP', '数据库分支'], examples: ['查看 Neon 项目', '检查开发数据库分支'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'mcp', popularity: 'GitHub 约 624 星；2026-08-16 快照',
        extensionTypes: ['plugin'],
        goal: '请为 Neon MCP 设计最小权限的开发环境连接，先列出可用工具和可能的数据库写操作，不连接生产项目。',
        addMethod: '在 Harness 用户 Profile 创建 MCP 配置，使用测试项目和受限密钥验证只读查询，再按需开放单项工具。',
        checks: ['默认开发项目', '高风险 SQL 单独确认', '提供撤销 Token 和删除配置方法'], source: 'Neon 官方 MCP 仓库', license: 'MIT', repositoryUrl: 'https://github.com/neondatabase/mcp-server-neon',
    }),
    shortAbility({
        id: 'mongodb-mcp-server', title: 'mongodb-js/mongodb-mcp-server',
        outcome: '让 Harness 查询 MongoDB 数据库和 Atlas 集群信息。',
        summary: 'MongoDB 官方 MCP，适合结构查看、查询和开发排错；应限制数据库、集合和写权限。',
        industryIds: ['programmer', 'retail', 'financial-services'], kindIds: ['coding', 'data-analysis', 'agents'], aliases: ['MongoDB MCP', 'Atlas MCP', 'NoSQL'], examples: ['查看集合结构', '检查 Atlas 开发集群'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'mcp', popularity: 'GitHub 约 1.1K 星；2026-08-16 快照',
        extensionTypes: ['plugin'],
        goal: '请用 MongoDB 官方 MCP 创建只访问指定开发数据库的连接，先列工具、集合范围和读写边界。',
        addMethod: '使用只读数据库用户和测试集群配置 MCP；先验证 list 和 find 等低风险工具，不默认开放 delete 或 update。',
        checks: ['数据库与集合白名单', '默认只读用户', '敏感字段不进入聊天记录'], source: 'MongoDB 官方 MCP 仓库', license: 'Apache-2.0', repositoryUrl: 'https://github.com/mongodb-js/mongodb-mcp-server',
    }),
    shortAbility({
        id: 'redis-mcp-server', title: 'redis/mcp-redis',
        outcome: '通过自然语言检查和管理 Redis 数据。',
        summary: 'Redis 官方 MCP，适合缓存与向量数据排查；必须限制实例、Key 范围和破坏性命令。',
        industryIds: ['programmer', 'retail', 'financial-services'], kindIds: ['coding', 'data-analysis', 'agents'], aliases: ['Redis MCP', '缓存', '向量检索'], examples: ['查看缓存 Key', '检查 Redis 数据类型'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'mcp', popularity: 'GitHub 约 568 星；2026-08-16 快照',
        extensionTypes: ['plugin'],
        goal: '请为 Redis MCP 创建开发实例的只读检查方案，先列出命令白名单和 Key 前缀，不执行 FLUSH、DEL 等破坏性操作。',
        addMethod: '在隔离 Profile 连接测试 Redis，先开放查询和扫描工具；生产连接、写命令和大范围扫描必须另行确认。',
        checks: ['禁止破坏性命令', '限制 Key 前缀和扫描数量', '凭据只放环境变量'], source: 'Redis 官方 MCP 仓库', license: 'MIT', repositoryUrl: 'https://github.com/redis/mcp-redis',
    }),
    shortAbility({
        id: 'awslabs-mcp', title: 'awslabs/mcp',
        outcome: '为 AWS 文档、基础设施、数据和运维工作接入专项 MCP。',
        summary: 'AWS Labs 官方 MCP 集合，覆盖文档、IaC、Serverless、数据库和成本；应按单个服务启用。',
        industryIds: ['programmer', 'financial-services', 'retail', 'government'], kindIds: ['coding', 'agents', 'research'], aliases: ['AWS MCP', 'AWS 文档', 'IaC MCP', '云运维'], examples: ['查询最新 AWS 文档', '检查 CDK 配置'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'mcp', popularity: 'GitHub 约 9.6K 星；2026-08-16 快照',
        extensionTypes: ['plugin'],
        goal: '请从 awslabs/mcp 中选择一个与当前任务直接相关的 MCP Server，先说明 IAM 权限、transport 和写操作，再用最小权限配置。',
        addMethod: '不要安装整套服务；只配置一个官方 MCP Server，优先文档或只读工具，并固定包版本。',
        checks: ['单个服务启用', 'IAM 最小权限', 'Cloud 写操作逐次确认并可审计'], source: 'AWS Labs 官方 MCP 仓库', license: 'Apache-2.0', repositoryUrl: 'https://github.com/awslabs/mcp',
    }),
    shortAbility({
        id: 'docker-mcp-gateway', title: 'docker/mcp-gateway',
        outcome: '用 Docker MCP Gateway 集中运行、隔离和管理 MCP Server。',
        summary: 'Docker 官方 MCP 网关与 CLI 插件，适合统一服务发现、容器隔离和凭据边界。',
        industryIds: ['programmer'], kindIds: ['coding', 'agents'], aliases: ['Docker MCP', 'MCP Gateway', '容器隔离'], examples: ['把多个 MCP 放进容器', '统一管理 MCP 服务'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 1.5K 星；2026-08-16 快照',
        extensionTypes: ['plugin'],
        goal: '请评估 Docker MCP Gateway 是否适合当前 Harness，先列容器、端口、挂载、Secret 和网络范围，再设计最小连接。',
        addMethod: '先在本地 Docker 测试一个只读 MCP；只挂载必要目录，禁止 Docker Socket 和主机根目录暴露。',
        checks: ['最小目录挂载', 'Secret 不写入镜像', '停止容器即可完整停用'], source: 'Docker 官方 MCP Gateway 仓库', license: 'MIT', repositoryUrl: 'https://github.com/docker/mcp-gateway',
    }),
    shortAbility({
        id: 'crawl4ai', title: 'unclecode/crawl4ai',
        outcome: '把网页转换成适合 LLM 使用的结构化内容。',
        summary: '高星开源爬虫，支持异步抓取、动态页面和结构化提取，适合项目级采集 Skill。',
        industryIds: ['programmer', 'retail', 'education'], kindIds: ['research', 'data-analysis', 'coding'], aliases: ['Crawl4AI', '网页爬虫', '结构化提取'], examples: ['抓取一个公开文档站', '把网页变成 Markdown'],
        ecosystem: 'community', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 78.3K 星；2026-08-16 快照',
        extensionTypes: ['skill', 'plugin'],
        goal: '请用 Crawl4AI 为我指定的公开站点设计小范围采集任务，先检查 robots、许可、URL 范围和请求频率。',
        addMethod: '在独立 Python 环境固定版本，先抓取一个公开页面并验证输出；再封装为只接受用户指定 URL 的 Harness Skill。',
        checks: ['遵守站点规则', '限制域名和并发', '保留来源 URL 和抓取时间'], source: 'Crawl4AI 维护者仓库', license: 'Apache-2.0', repositoryUrl: 'https://github.com/unclecode/crawl4ai',
    }),
    shortAbility({
        id: 'apify-mcp-server', title: 'apify/apify-mcp-server',
        outcome: '通过 MCP 调用 Apify 的网页抓取和自动化 Actors。',
        summary: 'Apify 官方 MCP，覆盖网页、搜索、地图、电商和社交数据；可能产生费用，必须显式选择 Actor。',
        industryIds: ['programmer', 'retail'], kindIds: ['research', 'data-analysis', 'agents'], aliases: ['Apify MCP', 'Actor', '网页采集'], examples: ['调用一个公开网页 Actor', '采集电商公开页面'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'mcp', popularity: 'GitHub 约 3.9K 星；2026-08-16 快照',
        extensionTypes: ['plugin'],
        goal: '请为 Apify MCP 选择一个明确 Actor，先展示输入、预计费用、数据范围和输出，不自动运行付费任务。',
        addMethod: '在 Harness MCP Client 中配置官方服务器和用户 Token；先用免费或低成本只读 Actor 做最小验证。',
        checks: ['运行前显示费用', 'Actor 与域名白名单', 'Token 不进入仓库和聊天输出'], source: 'Apify 官方 MCP 仓库', license: 'MIT', repositoryUrl: 'https://github.com/apify/apify-mcp-server',
    }),
    shortAbility({
        id: 'langgraph', title: 'langchain-ai/langgraph',
        outcome: '构建有状态、可恢复和可人工介入的 Agent 工作流。',
        summary: '高星 Agent 编排框架，适合把复杂流程拆成图和状态机；属于项目级框架，不是直接安装的 Harness Skill。',
        industryIds: ['programmer'], kindIds: ['coding', 'agents'], aliases: ['LangGraph', 'Agent 状态机', '工作流编排'], examples: ['设计一个可恢复工作流', '给 Agent 增加人工批准节点'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 39.8K 星；2026-08-16 快照',
        extensionTypes: ['workflow', 'skill'],
        goal: '请参考 LangGraph 的状态、节点和人工介入设计，为当前 Harness 任务先画出最小工作流；只有确实需要独立运行时才创建项目。',
        addMethod: '先把思路转成 Harness Workflow 或 Skill；若必须使用 LangGraph，在独立项目固定版本并提供启动、测试和停止命令。',
        checks: ['状态可查看和恢复', '外部写操作有人工节点', '失败不会静默跳过'], source: 'LangGraph 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/langchain-ai/langgraph',
    }),
    shortAbility({
        id: 'microsoft-autogen', title: 'microsoft/autogen',
        outcome: '参考多 Agent 消息协作、工具调用和运行时设计。',
        summary: 'Microsoft 的 Agent 框架，适合研究复杂多 Agent 系统；简单 Harness 任务不应为它额外搭框架。',
        industryIds: ['programmer'], kindIds: ['coding', 'agents'], aliases: ['AutoGen', '多 Agent', 'Agent Framework'], examples: ['设计多 Agent 协作', '研究 Agent 消息协议'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'project-tool', popularity: 'GitHub 约 60.5K 星；2026-08-16 快照',
        extensionTypes: ['workflow', 'skill'],
        goal: '请比较 AutoGen 与当前 Harness 的 Agent Preset、Subagent 和 Workflow，只有确认存在必要缺口时才设计独立项目。',
        addMethod: '先做架构对比和最小原型，不直接把 AutoGen 运行时塞进 Harness；所有 Agent 工具和权限需显式列出。',
        checks: ['避免重复 Harness 已有能力', 'Agent 权限逐个声明', '提供停止整个运行时的方法'], source: 'Microsoft 官方 AutoGen 仓库', license: 'CC-BY-4.0（仓库当前声明）', repositoryUrl: 'https://github.com/microsoft/autogen',
    }),
    shortAbility({
        id: 'crewai', title: 'crewAIInc/crewAI',
        outcome: '用角色、任务和流程组织多个 Agent 协作。',
        summary: '高星多 Agent 框架，适合独立自动化项目；能力中心主要借鉴其角色与任务拆分思路。',
        industryIds: ['programmer', 'retail'], kindIds: ['coding', 'agents'], aliases: ['CrewAI', '多 Agent', '角色工作流'], examples: ['把调研拆给多个 Agent', '做一个角色化自动化流程'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 57.2K 星；2026-08-16 快照',
        extensionTypes: ['workflow', 'skill'],
        goal: '请参考 CrewAI 的角色、任务和流程结构，为当前需求先设计 Harness 原生 Workflow；只有原生机制不足时才创建 CrewAI 项目。',
        addMethod: '先用三个以内角色做隔离原型，明确每个角色的工具、输入输出和失败处理，不自动连接生产服务。',
        checks: ['角色不共享多余凭据', '任务输入输出可追溯', '流程可以整体停止和重跑'], source: 'CrewAI 维护者仓库', license: 'MIT', repositoryUrl: 'https://github.com/crewAIInc/crewAI',
    }),
    shortAbility({
        id: 'agno', title: 'agno-agi/agno',
        outcome: '构建、运行和管理带工具、知识与记忆的 Agent 平台。',
        summary: '高星 Agent 平台框架，适合独立服务与团队项目；个人 Harness 应先复用原生能力。',
        industryIds: ['programmer'], kindIds: ['coding', 'agents'], aliases: ['Agno', 'Agent Platform', '知识与记忆'], examples: ['搭建 Agent 服务', '研究 Agent 平台架构'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 41.7K 星；2026-08-16 快照',
        extensionTypes: ['workflow', 'plugin'],
        goal: '请比较 Agno 与 Harness 的工具、知识、记忆和运行方式，只为无法用原生机制完成的部分设计独立服务。',
        addMethod: '先在隔离目录运行最小示例，并通过一个受限 MCP 或 HTTP 接口接入 Harness，不共享整个本机环境。',
        checks: ['服务边界明确', '凭据和知识目录最小化', '停止服务后 Harness 可正常运行'], source: 'Agno 维护者仓库', license: 'Apache-2.0', repositoryUrl: 'https://github.com/agno-agi/agno',
    }),
    shortAbility({
        id: 'nvidia-skills', title: 'NVIDIA/skills',
        outcome: '安装 NVIDIA 官方验证的 CUDA、AI、仿真和机器人 Agent Skills。',
        summary: '官方 Skill 目录，适合 GPU、RAG、机器人和科学计算开发；应按产品和硬件选择单项。',
        industryIds: ['programmer', 'life-sciences', 'education'], kindIds: ['coding', 'data-analysis', 'agents'], aliases: ['NVIDIA Skills', 'CUDA Skill', '机器人', 'RAG'], examples: ['查一个 CUDA 工作流 Skill', '做机器人仿真任务'],
        ecosystem: 'vendor', trust: 'vendor-official', compatibility: 'skill-copy', popularity: 'GitHub 约 3K 星；2026-08-16 快照',
        extensionTypes: ['skill'],
        goal: '请从 NVIDIA/skills 选择一个与当前硬件和任务匹配的官方 Skill，先检查 GPU、驱动、SDK、许可证和磁盘需求。',
        addMethod: '使用仓库列出的标准 Skills 安装方式选择单项；先在测试项目验证，不下载无关模型或整套目录。',
        checks: ['确认硬件和驱动', '单项 Skill 安装', '模型与缓存位置可查看和删除'], source: 'NVIDIA 官方 Agent Skills 仓库', license: 'Apache-2.0', repositoryUrl: 'https://github.com/NVIDIA/skills',
    }),
    shortAbility({
        id: 'trivy', title: 'aquasecurity/trivy',
        outcome: '扫描代码、容器、依赖、Secret、SBOM 和云配置风险。',
        summary: '高星安全扫描器，适合把只读安全检查加入开发流程；修复和删除操作应分开确认。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'government'], kindIds: ['coding', 'agents'], aliases: ['Trivy', '漏洞扫描', 'Secret 扫描', 'SBOM'], examples: ['扫描容器镜像', '检查仓库依赖和密钥'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 37.4K 星；2026-08-16 快照',
        extensionTypes: ['skill', 'plugin'],
        goal: '请用 Trivy 对指定项目或镜像执行只读扫描，先展示命令、范围、数据库更新时间和输出位置，不自动修复或删除文件。',
        addMethod: '在项目级环境固定版本，先扫描测试目标并输出 JSON/SARIF；再把只读命令封装成 Harness Skill。',
        checks: ['范围由用户指定', 'Secret 只显示脱敏摘要', '扫描结果需人工复核'], source: 'Aqua Security Trivy 维护者仓库', license: 'Apache-2.0', repositoryUrl: 'https://github.com/aquasecurity/trivy',
    }),
    shortAbility({
        id: 'semgrep', title: 'semgrep/semgrep',
        outcome: '用代码模式查找多语言项目中的 Bug、安全和规范问题。',
        summary: '成熟静态分析工具，适合代码审查和 CI；规则来源、误报和自动修复必须可见。',
        industryIds: ['programmer', 'financial-services', 'healthcare', 'government'], kindIds: ['coding', 'agents'], aliases: ['Semgrep', '静态分析', '代码安全', 'SAST'], examples: ['检查常见安全问题', '在 CI 中运行代码规则'],
        ecosystem: 'vendor', trust: 'maintainer', compatibility: 'project-tool', popularity: 'GitHub 约 16.2K 星；2026-08-16 快照',
        extensionTypes: ['skill', 'plugin'],
        goal: '请用 Semgrep 对指定目录运行一组明确来源的只读规则，先说明规则集、网络访问和输出，不启用自动修复。',
        addMethod: '在项目环境固定 CLI 与规则版本，先运行小范围扫描；确认误报后再加入 Harness 或 CI 工作流。',
        checks: ['固定规则版本', '误报由人工复核', '默认不自动修改代码'], source: 'Semgrep 维护者仓库', license: 'LGPL-2.1', repositoryUrl: 'https://github.com/semgrep/semgrep',
    }),
];
